Kubeinit/kubeinit

kubeinit/roles/kubeinit_k8s/tasks/00_configure_common.yml
kubeinit/roles/kubeinit_libvirt/tasks/10_k8s_deploy_nodes.yml
kubeinit/roles/kubeinit_libvirt/tasks/10_okd_deploy_service_nodes.yml
kubeinit/roles/kubeinit_okd/tasks/10_configure_service_nodes.yml
kubeinit/roles/kubeinit_okd/tasks/30_post_deployment_tasks.yml
kubeinit/roles/kubeinit_rke/tasks/40_deploy_rke.yml

Current libguestfs 1.40.2 fails with
virt-resize: error: libguestfs error: f2fs: unknown group

Fix: move from virt-resize to qemu-img resize

---

kubeinit/roles/kubeinit_okd/defaults/main.yml
kubeinit/roles/kubeinit_okd/tasks/10_configure_service_nodes.yml
kubeinit/roles/kubeinit_okd/templates/install-config.yaml.j2
kubeinit/roles/kubeinit_rke/defaults/main.yml
kubeinit/roles/kubeinit_rke/templates/cluster.yml.j2

This patch organizes better the
template configs for deploying okd and rke.

refactor: code split

---

kubeinit/roles/kubeinit_submariner/tasks/10_configure_broker.yml
kubeinit/roles/kubeinit_submariner/tasks/20_configure_secondary.yml

This patch adjust both broker and secondary
cluster deployment.

fix: adjust subctl commands

---

kubeinit/roles/kubeinit_submariner/tasks/20_configure_secondary.yml

This patch makes the join cluster command non interactive.
Also removes some comments in the scrips first line.

fix: include no-label and remove comment from script

---

ci/launch_e2e.py
ci/run.sh
ci/submariner.sh
kubeinit/roles/kubeinit_submariner/tasks/10_configure_broker.yml
kubeinit/roles/kubeinit_submariner/tasks/20_configure_secondary.yml

This patch adds the submariner job.

feat: include submariner job

---

kubeinit/roles/kubeinit_submariner/defaults/main.yml
kubeinit/roles/kubeinit_submariner/tasks/10_join_clusters.yml
kubeinit/roles/kubeinit_submariner/tasks/20_verify_deployment.yml
kubeinit/roles/kubeinit_submariner/templates/netshoot_name.sh.j2

This patch adds a new role variable to make
globalnet optinal.

feat: make globalnet configurable

---

kubeinit/roles/kubeinit_okd/defaults/main.yml
kubeinit/roles/kubeinit_okd/templates/install-config.yaml.j2

This change moves the pullsecret JSON data in
the OKD role as a variable.

refactor: move auth pullsecret as a role variable

---

ci/launch_submariner_operator.py
ci/run-submariner.sh
kubeinit/roles/kubeinit_submariner/defaults/main.yml
kubeinit/roles/kubeinit_submariner/tasks/00_configure_common.yml

This patch adds a PoC for building the container
images for the submariner-operator repo based on a PR.

feat: include submariner container image build deployments

---

kubeinit/hosts/cdk/inventory
kubeinit/hosts/k8s/inventory
kubeinit/hosts/okd/inventory
kubeinit/hosts/rke/inventory
kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_libvirt/tasks/10_k8s_deploy_nodes.yml
kubeinit/roles/kubeinit_libvirt/tasks/10_okd_deploy_service_nodes.yml
kubeinit/roles/kubeinit_libvirt/tasks/10_rke_deploy_nodes.yml
kubeinit/roles/kubeinit_libvirt/templates/ifcfg-eth1.j2

This patch adds support for adding a fixed mac
address to the external interface in the service node.
Close #82 
Co-Authored-By: Carlos Camacho <17335512+ccamacho@users.noreply.github.com>

feat: add fixed mac address to the external interface

---

kubeinit/galaxy.yml

This releases KubeInit's 0.6.0

chore: cut 0.6.0

---

ci/run_submariner.sh
kubeinit/roles/kubeinit_submariner/tasks/00_configure_common.yml

This patch adds some debung information
when getting the submariner operator code

chore: print PR inf in the submariner playbook

---

kubeinit/roles/kubeinit_submariner/defaults/main.yml
kubeinit/roles/kubeinit_submariner/tasks/00_configure_common.yml

Its needed to move from docker as it fails
multiple times with a too many requests failure.

fix: docker.io breaks with too many requests

---

.github/workflows/release.yml
kubeinit/galaxy.yml
tools/release.sh

After each release we push a new tag to quay

chore: add container image in quay

---

docs/src/howtos_and_presentations.rst
docs/src/usage.rst
kubeinit/README.md

This patch updates the readme
with the way to run kubeinit
from a quay container and a
docs update.

chore: update readme

---

docs/src/usage.rst

chore: docs fix

---

ci/launch_e2e.py
ci/launch_submariner_operator.py

WE had issues to push the CI logs with binary
files, this patch fix that issue and commits only
one change.

fix: merge CI logs in a single commit

---

ci/ara.sh
ci/kubeinit_ci_utils.py
ci/launch_e2e.py
ci/launch_submariner_operator.py
ci/run.sh
ci/run_submariner.sh
kubeinit/playbooks/submariner-subctl-verify.yml
kubeinit/roles/kubeinit_submariner/defaults/main.yml
kubeinit/roles/kubeinit_submariner/tasks/00_configure_common.yml
kubeinit/roles/kubeinit_submariner/tasks/20_check_connection.yml
kubeinit/roles/kubeinit_submariner/tasks/30_subctl_verify.yml
kubeinit/roles/kubeinit_submariner/tasks/main.yml
kubeinit/roles/kubeinit_validations/tasks/main.yml

This patch adds an new playbook for running
subctl verify so the CI logs are in a different
section.

feat: include subctl verify as a new playbook

---

docs/src/README.md
docs/src/_exts/ansible-autodoc.py
test-requirements.txt

This patch adds the readme file as part of the documentation.

docs: add readme as part of docs

---

_skeleton_role_/README.md.j2
kubeinit/roles/kubeinit_apache/README.md
kubeinit/roles/kubeinit_bind/README.md
kubeinit/roles/kubeinit_cdk/README.md
kubeinit/roles/kubeinit_haproxy/README.md
kubeinit/roles/kubeinit_k8s/README.md
kubeinit/roles/kubeinit_kubevirt/README.md
kubeinit/roles/kubeinit_libvirt/README.md
kubeinit/roles/kubeinit_nfs/README.md
kubeinit/roles/kubeinit_okd/README.md
kubeinit/roles/kubeinit_registry/README.md
kubeinit/roles/kubeinit_rke/README.md
kubeinit/roles/kubeinit_submariner/README.md
kubeinit/roles/kubeinit_validations/README.md

This patch cleans up some unneeded titles
in the roles.

chore: clean unneeded titles

---

ci/launch_e2e.py
ci/launch_submariner_operator.py
ci/run.sh
ci/run_submariner.sh

This patch includes the date
in the patch names.

chore: include date in job name

---

kubeinit/roles/kubeinit_registry/tasks/00_install.yml
kubeinit/roles/kubeinit_registry/tasks/20_mirror_rke.yml
kubeinit/roles/kubeinit_rke/tasks/50_post_deployment_tasks.yml
kubeinit/roles/kubeinit_submariner/tasks/00_configure_common.yml

This patch enables insecure registries in OKD when using with
docker.

fix: allow insecure registry with docker in OKD

---

.github/workflows/docs_build_pr.yml
.github/workflows/release.yml
kubeinit/requirements.yml

This patch excludes common.yml from the
docs graphing tooling.

fix: remove common.yml from the inventory grapher

---

Dockerfile
docs/src/usage.rst
kubeinit/galaxy.yml

This patch builds a new release
and amends the documentation.

chore: release and update docs.

---

docs/src/contributing.rst
docs/src/usage.rst
kubeinit/README.md

This patch removes some unneeded notes

docs: remove unneeded notes

---

docs/src/contributing.rst

docs: fix link

---

kubeinit/roles/kubeinit_nfs/tasks/main.yml
kubeinit/roles/kubeinit_okd/tasks/10_configure_service_nodes.yml
kubeinit/roles/kubeinit_okd/tasks/30_post_deployment_tasks.yml

refactor: adds nfs storage class and moves nfs config to post deployment

---

kubeinit/roles/kubeinit_cdk/tasks/10_configure_service_nodes.yml
kubeinit/roles/kubeinit_cdk/tasks/50_post_deployment_tasks.yml
kubeinit/roles/kubeinit_eks/tasks/10_configure_service_nodes.yml
kubeinit/roles/kubeinit_eks/tasks/40_post_deployment_tasks.yml
kubeinit/roles/kubeinit_k8s/tasks/10_configure_service_nodes.yml
kubeinit/roles/kubeinit_k8s/tasks/40_post_deployment_tasks.yml
kubeinit/roles/kubeinit_nfs/tasks/main.yml
kubeinit/roles/kubeinit_rke/tasks/10_configure_service_nodes.yml
kubeinit/roles/kubeinit_rke/tasks/50_post_deployment_tasks.yml

chore: do not merge

---

kubeinit/playbooks/cdk.yml
kubeinit/playbooks/eks.yml
kubeinit/playbooks/k8s.yml
kubeinit/playbooks/okd.yml
kubeinit/playbooks/rke.yml
kubeinit/playbooks/submariner-subctl-verify.yml
kubeinit/playbooks/submariner.yml
kubeinit/roles/kubeinit_cdk/tasks/50_post_deployment_tasks.yml
kubeinit/roles/kubeinit_eks/tasks/40_post_deployment_tasks.yml
kubeinit/roles/kubeinit_k8s/tasks/40_post_deployment_tasks.yml
kubeinit/roles/kubeinit_nfs/tasks/main.yml
kubeinit/roles/kubeinit_okd/tasks/30_post_deployment_tasks.yml
kubeinit/roles/kubeinit_rke/tasks/50_post_deployment_tasks.yml

This patch fixes somw wrong identation
in the NFS templates.

fix: fix template indentation

---

kubeinit/galaxy.yml

chore: release 0.6.4

---

kubeinit/roles/kubeinit_okd/defaults/main.yml

This patch bumps the default deployed version
of OKD to 4.6

feat: deploy OKD 4.6

---

.gitignore
ci/kubeinit_ci_utils.py
ci/launch_submariner_operator.py

This patch triggers submariner jobs
and update its labels and status
accordingly.

feat: trigger submariner jobs

---

ci/launch_e2e_periodic.py
kubeinit/README.md

This patch simplifies the project's
readme file.

chore: update readme content

---

ci/run_kubeinit.sh
ci/run_periodic.sh
ci/run_submariner.sh

chore: test

---

.github/workflows/release.yml
agent/MANIFEST.in
agent/kubeinit/__init__.py
agent/kubeinit/cli.py
agent/kubeinit/const.py
agent/kubeinit/get_banner.py
agent/kubeinit/lib.py
agent/kubeinit/logger.py
agent/requirements.txt
agent/setup.py
agent/tests/test_sample.py
kubeinit/galaxy.yml
tools/check_version.sh
tools/pypi_publish.sh
tox.ini

This patch adds a simple skeleton code for the agent

feat: add simple agent skeleton

---

.github/workflows/molecule.yml
ui/app/base/static/assets/brand/pystol_full_big.svg
ui/app/base/templates/base-site-fullscreen.html
ui/app/base/templates/base-site.html

This patch updates some templates and logos.

chore: template updates and logo img

---

ui/app/available/routes.py
ui/app/base/k8s.py
ui/app/base/routes.py
ui/app/base/templates/site_template/footer.html
ui/app/base/templates/site_template/navigation.html
ui/app/executed/routes.py
ui/app/faq/routes.py
ui/app/home/routes.py
ui/app/namespaces/routes.py
ui/app/nodes/routes.py
ui/app/pods/routes.py
ui/app/run/routes.py
ui/app/run/templates/run.html
ui/app/usage/routes.py

This patch updates some misc variables

fix: update variables

---

tools/check_version.sh
ui/app/available/routes.py
ui/app/base/routes.py
ui/app/base/templates/site_template/navigation.html
ui/app/executed/routes.py
ui/app/faq/routes.py
ui/app/home/routes.py
ui/app/namespaces/routes.py
ui/app/nodes/routes.py
ui/app/pods/routes.py
ui/app/run/routes.py
ui/app/usage/routes.py
ui/app/version.py

docs: update link

---

.gitignore
kubeinit/hosts/cdk/inventory
kubeinit/hosts/eks/inventory
kubeinit/hosts/k8s/inventory
kubeinit/hosts/okd/inventory
kubeinit/hosts/rke/inventory
kubeinit/playbooks/okd.yml
kubeinit/roles/kubeinit_validations/tasks/20_libvirt_free_space.yml

This is the first series of patches to add support for
multiple hypervisors.
This updates the inventory files and updates the
disk space validation.

feat: include initial support for multiple hypervisors

---

kubeinit/hosts/eks/inventory
kubeinit/hosts/k8s/inventory
kubeinit/hosts/rke/inventory
kubeinit/playbooks/cdk.yml
kubeinit/playbooks/eks.yml
kubeinit/playbooks/k8s.yml
kubeinit/playbooks/rke.yml
kubeinit/playbooks/submariner-subctl-verify.yml
kubeinit/playbooks/submariner.yml

We missed to comment the hypervisors in
some distros, breaking the disk space validation.

fix: adjust missing inventory files

---

kubeinit/roles/kubeinit_cdk/tasks/10_configure_service_nodes.yml
kubeinit/roles/kubeinit_cdk/tasks/50_post_deployment_tasks.yml
kubeinit/roles/kubeinit_eks/tasks/00_configure_service_nodes.yml
kubeinit/roles/kubeinit_eks/tasks/10_configure_common.yml

This patch removes a few unneeded tags and tasks.

fix: remove unneeded tasks and tags

---

kubeinit/roles/kubeinit_cdk/tasks/main.yml

Execute the common steps in all the cdk nodes.

fix: install docker everywhere in cdk

---

.github/workflows/linters.yml
kubeinit/roles/kubeinit_eks/tasks/30_configure_worker_nodes.yml

There is a wrong conditional breaking eks
deployments with a single master node.

fix: register correctly eks worker nodes.

---

kubeinit/roles/kubeinit_libvirt/tasks/00_ovn_setup.yml
kubeinit/roles/kubeinit_libvirt/tasks/main.yml

This PR includes the steps for configuring OVN
in a multi-HV environment.

feat: include OVN configuration steps

---

kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_libvirt/tasks/00_linux_bridge_setup.yml
kubeinit/roles/kubeinit_libvirt/tasks/00_ovn_setup.yml
kubeinit/roles/kubeinit_libvirt/tasks/main.yml

Added some minor fixes for the OVN deployment.

fix: adjust OVN config deployment

---

kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_libvirt/tasks/00_ovn_setup.yml

This patch adds the OVN configuration parameters
available from the role defaults.

feat: make OVN parameters available from the role defaults

---

tools/check_fqcn.py
tox.ini

This patch checks that all tasks use fqcn
Please enter the commit message for your changes. Lines starting

dev: lint the fqcn playbooks

---

kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_libvirt/tasks/00_ovn_install.yml
kubeinit/roles/kubeinit_libvirt/tasks/00_ovn_setup.yml
kubeinit/roles/kubeinit_libvirt/tasks/main.yml
kubeinit/roles/kubeinit_libvirt/templates/cluster-net.xml.j2

This patch allows to deploy
Kubeinit using OVN.

feat: allow deployments using OVN

---

kubeinit/hosts/cdk/inventory
kubeinit/hosts/eks/inventory
kubeinit/hosts/k8s/inventory
kubeinit/hosts/okd/inventory
kubeinit/hosts/rke/inventory
kubeinit/roles/kubeinit_cdk/tasks/main.yml
kubeinit/roles/kubeinit_eks/tasks/main.yml
kubeinit/roles/kubeinit_k8s/tasks/main.yml
kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_libvirt/tasks/00_ovn_install.yml
kubeinit/roles/kubeinit_libvirt/tasks/00_ovn_post_setup.yml
kubeinit/roles/kubeinit_libvirt/tasks/00_ovn_setup.yml
kubeinit/roles/kubeinit_libvirt/tasks/10_k8s_deploy_nodes.yml
kubeinit/roles/kubeinit_libvirt/tasks/10_okd_deploy_nodes.yml
kubeinit/roles/kubeinit_libvirt/tasks/10_rke_deploy_nodes.yml
kubeinit/roles/kubeinit_okd/tasks/main.yml
kubeinit/roles/kubeinit_rke/tasks/main.yml
kubeinit/roles/kubeinit_validations/tasks/20_libvirt_free_space.yml

This patch adds a post deployment step for OVN.

feat: add post OVN deployment steps

---

kubeinit/roles/kubeinit_libvirt/defaults/main.yml

OVN is no ready yet, so dont enable it.

fix: do not enable OVN yet

---

Dockerfile
kubeinit/galaxy.yml
kubeinit/requirements.yml
kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_libvirt/tasks/00_ovn_post_setup.yml
kubeinit/roles/kubeinit_libvirt/tasks/00_ovn_setup.yml
kubeinit/roles/kubeinit_libvirt/tasks/main.yml
kubeinit/roles/kubeinit_libvirt/templates/cluster-net.xml.j2
kubeinit/roles/kubeinit_libvirt/templates/detach.sh
tools/sanity.sh
tools/units.sh
tox.ini

This PR adds more steps for the OVN
configuration NAT+DHCP

feat: add more OVN steps

---

ci/run_kubeinit.sh
ci/run_submariner.sh

This PR includes a missing parameter to update
an internal DNS.

fix: include internal dns in CI deployments

---

kubeinit/roles/kubeinit_bind/templates/named.conf.j2
kubeinit/roles/kubeinit_bind/templates/named.conf.local.j2

This patch allows to forward requests
between multiple clusters.

fix: allow bind to forward requests

---

kubeinit/roles/kubeinit_libvirt/tasks/00_cleanup.yml
kubeinit/roles/kubeinit_libvirt/tasks/main.yml
kubeinit/roles/kubeinit_okd/tasks/30_post_deployment_tasks.yml
tox.ini

This PR makes easier to execute only the cleanup tasks.

feat: split the cleanup tasks in a separate file

---

kubeinit/hosts/cdk/inventory
kubeinit/hosts/eks/inventory
kubeinit/hosts/k8s/inventory
kubeinit/hosts/okd/inventory
kubeinit/hosts/rke/inventory
kubeinit/roles/kubeinit_libvirt/tasks/00_cleanup.yml
kubeinit/roles/kubeinit_libvirt/tasks/20_check_nodes_up.yml
kubeinit/roles/kubeinit_libvirt/tasks/main.yml

This PR reverts some changes to
the way ssh and Ansible behaves.

fix: adjust inventory to honor the ssh proxy

---

kubeinit/roles/kubeinit_libvirt/tasks/00_cleanup.yml
kubeinit/roles/kubeinit_libvirt/tasks/00_ovn_post_setup.yml
kubeinit/roles/kubeinit_libvirt/tasks/10_k8s_deploy_nodes.yml
kubeinit/roles/kubeinit_libvirt/tasks/10_okd_deploy_nodes.yml

This PR includes the OVN cleaning tasks and
install Python3 in the CentOS guests.

feat: include OVN clean tasks in the cleanup file

---

kubeinit/hosts/cdk/inventory
kubeinit/hosts/eks/inventory
kubeinit/hosts/k8s/inventory
kubeinit/hosts/okd/inventory
kubeinit/hosts/rke/inventory
kubeinit/roles/kubeinit_cdk/defaults/main.yml
kubeinit/roles/kubeinit_cdk/tasks/00_bounce_packages.yml
kubeinit/roles/kubeinit_eks/defaults/main.yml
kubeinit/roles/kubeinit_eks/tasks/00_bounce_packages.yml
kubeinit/roles/kubeinit_k8s/defaults/main.yml
kubeinit/roles/kubeinit_k8s/tasks/00_bounce_packages.yml
kubeinit/roles/kubeinit_libvirt/tasks/00_cleanup.yml
kubeinit/roles/kubeinit_libvirt/tasks/10_k8s_deploy_nodes.yml
kubeinit/roles/kubeinit_libvirt/tasks/10_okd_deploy_nodes.yml
kubeinit/roles/kubeinit_libvirt/tasks/10_rke_deploy_nodes.yml
kubeinit/roles/kubeinit_libvirt/tasks/20_check_nodes_up.yml
kubeinit/roles/kubeinit_libvirt/tasks/main.yml
kubeinit/roles/kubeinit_okd/defaults/main.yml
kubeinit/roles/kubeinit_okd/tasks/00_bounce_packages.yml
kubeinit/roles/kubeinit_okd/tasks/20_check_nodes_ready.yml
kubeinit/roles/kubeinit_okd/tasks/30_post_deployment_tasks.yml
kubeinit/roles/kubeinit_rke/defaults/main.yml
kubeinit/roles/kubeinit_rke/tasks/00_bounce_packages.yml

This patch configures the SSH config file instead
of the Ansible proxy settings, Ansible for some
reason is not honoring them anymore.

fix: use local ssh config instead of proxy settings

---

kubeinit/roles/kubeinit_libvirt/defaults/main.yml

This PR updates the version of fcos to fcos33

chore: update version of fcos

---

.github/workflows/release.yml

This commit after every merge, will push the latest version to GitLab.

chore: mirror to GitLab

---

kubeinit/roles/kubeinit_okd/tasks/30_check_bootstrap_complete.yml
kubeinit/roles/kubeinit_okd/tasks/30_post_deployment_tasks.yml
kubeinit/roles/kubeinit_okd/tasks/main.yml

This commit force the deployment
to wait until the bootstrap step completes.

fix: wait for bootstrap to complete

---

.gitlab-ci.yml
ci/launch_e2e_periodic.py

This commit parses correctly the
arguments.

fix: parse correctly args

---

.github/workflows/release.yml

This commit updates ansible in the job that
publishes the docs.

fix: update ansible in the docs release job

---

kubeinit/roles/kubeinit_libvirt/tasks/00_ovn_post_setup.yml
kubeinit/roles/kubeinit_libvirt/tasks/main.yml

This commit splits the OVN iptables rules
to allow adding the external interface details.

feat: split OVN nat rules

---

kubeinit/hosts/cdk/inventory
kubeinit/hosts/k8s/inventory
kubeinit/hosts/okd/inventory
kubeinit/hosts/rke/inventory
kubeinit/roles/kubeinit_libvirt/tasks/00_cleanup.yml
kubeinit/roles/kubeinit_libvirt/tasks/00_ovn_post_setup.yml
kubeinit/roles/kubeinit_libvirt/tasks/10_k8s_deploy_nodes.yml
kubeinit/roles/kubeinit_libvirt/tasks/10_okd_deploy_nodes.yml
kubeinit/roles/kubeinit_libvirt/tasks/10_rke_deploy_nodes.yml
kubeinit/roles/kubeinit_libvirt/tasks/20_check_nodes_up.yml
kubeinit/roles/kubeinit_libvirt/templates/cluster-net.xml.j2

This commit connects the service external interface
to the OVN network.

feat: add the external interface to OVN deployment

---

kubeinit/roles/kubeinit_libvirt/tasks/00_ovn_post_setup.yml
kubeinit/roles/kubeinit_libvirt/tasks/main.yml
kubeinit/roles/kubeinit_libvirt/templates/enslaver.sh

This commir helps to enslave the
physical interface.

fix: add enslaver helpers

---

kubeinit/roles/kubeinit_libvirt/tasks/00_ovn_post_setup.yml
kubeinit/roles/kubeinit_libvirt/templates/enslaver.sh

This commit is the last step to have
access to the external cluster interface.
This patches both OVS bridges from the
cluster network and the host physical interface.

fix: patch the external interface to the OVS bridge

---

kubeinit/hosts/cdk/inventory
kubeinit/hosts/eks/inventory
kubeinit/hosts/k8s/inventory
kubeinit/hosts/okd/inventory
kubeinit/hosts/rke/inventory
kubeinit/roles/kubeinit_libvirt/tasks/main.yml
kubeinit/roles/kubeinit_validations/tasks/20_libvirt_free_space.yml
kubeinit/roles/kubeinit_validations/tasks/30_libvirt_available_ram.yml
kubeinit/roles/kubeinit_validations/tasks/40_libvirt_check_cpu_cores.yml

This PR contains a set of 3 commits to address issues in the code base.
fix: replace stricthostkeychecking with StrictHostKeyChecking 
fix: update how we iterate over validation maps 
fix: update when conditions for external bridge checks

Kubeinit fixes

---

kubeinit/roles/kubeinit_bind/templates/named.conf.local.j2
kubeinit/roles/kubeinit_libvirt/tasks/00_cleanup.yml
kubeinit/roles/kubeinit_libvirt/tasks/00_ovn_post_setup.yml
kubeinit/roles/kubeinit_libvirt/tasks/main.yml
kubeinit/roles/kubeinit_libvirt/templates/101-cloudinit-hosts.tmpl.j2
kubeinit/roles/kubeinit_libvirt/templates/cluster-net.xml.j2
kubeinit/roles/kubeinit_validations/tasks/20_libvirt_free_space.yml
kubeinit/roles/kubeinit_validations/tasks/30_libvirt_available_ram.yml
kubeinit/roles/kubeinit_validations/tasks/40_libvirt_check_cpu_cores.yml
kubeinit/roles/kubeinit_validations/tasks/70_libvirt.yml

This PR contains a set of 3 commits to add enhancements to the code base.
feat: add view to bind for public bridge network 
feat: collect all of the non-hypervisor nodes into all_nodes group 
feat: replace ssh config.kubeinit file with ssh -o ProxyCommand

Kubeinit enhancements

---

agent/setup.py
kubeinit/galaxy.yml
kubeinit/roles/kubeinit_libvirt/tasks/00_ovn_post_setup.yml
kubeinit/roles/kubeinit_libvirt/tasks/00_prepare.yml
kubeinit/roles/kubeinit_libvirt/tasks/main.yml
kubeinit/roles/kubeinit_libvirt/templates/detach.sh.j2
ui/app/version.py
ui/package.json

This commit renders the detach script in the host that needs
to have external access to the service guest.

feat: render detach script in the external interface host

---

kubeinit/roles/kubeinit_bind/templates/internals_db.j2
kubeinit/roles/kubeinit_bind/templates/internals_db.local.j2
kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_libvirt/tasks/60_okd_deploy_nodes.yml
kubeinit/roles/kubeinit_okd/defaults/main.yml
kubeinit/roles/kubeinit_okd/tasks/10_configure_service_nodes.yml
kubeinit/roles/kubeinit_okd/templates/install-config.yaml.j2
kubeinit/roles/kubeinit_registry/defaults/main.yml
kubeinit/roles/kubeinit_registry/tasks/10_configure.yml
kubeinit/roles/kubeinit_registry/tasks/10_configure_okd.yml
kubeinit/roles/kubeinit_registry/tasks/20_mirror_okd.yml

This commit allows to deploy OpenShift from the
automation used to deploy OKD.

feat: allow to deploy OpenShift

---

kubeinit/roles/kubeinit_libvirt/tasks/main.yml

This commit adds a correct treeinfo file to deploy rhcos
images.

fix: adjust treeinfo for RHCOS

---

kubeinit/roles/kubeinit_libvirt/templates/detach.sh.j2

This commit adds the NetworkManager-ovs
in CentOS.

fix: include NetworkManager OVS package

---

kubeinit/roles/kubeinit_libvirt/templates/detach.sh.j2

This commit enables the interface just afet the manual IP is
configured.

fix: enable kiextbr0 interface after configuring the static IP

---

kubeinit/roles/kubeinit_libvirt/templates/detach.sh.j2

This commit includes the DNS servers when
configuring the external interface bridge.

fix: include dns server in static ip config

---

kubeinit/roles/kubeinit_eks/tasks/50_post_deployment_tasks.yml
kubeinit/roles/kubeinit_k8s/tasks/50_post_deployment_tasks.yml
kubeinit/roles/kubeinit_rke/tasks/70_post_deployment_services_tasks.yml

This commit disables NFS until the commands
changes from oc to kubectl.

fix: disable NFS if not OKD

---

agent/setup.py
kubeinit/galaxy.yml
ui/app/version.py
ui/package.json

This commit releases KubeInit 1.0.2.

chore: release 1.0.2

---

kubeinit/roles/kubeinit_nfs/tasks/main.yml

This commit increases the retries waiting
for the NFS resources to start.

fix: wait for 20 retries

---

kubeinit/roles/kubeinit_libvirt/defaults/main.yml

This commit will switch the VM we create for the service node from
CentOS 8.3.2011 to CentOS Stream.

feat: update service node from centos 8.3.2011 to 8-stream

---

kubeinit/roles/kubeinit_apache/defaults/main.yml
kubeinit/roles/kubeinit_apache/tasks/main.yml
kubeinit/roles/kubeinit_bind/defaults/main.yml
kubeinit/roles/kubeinit_bind/tasks/main.yml
kubeinit/roles/kubeinit_bind/templates/named.conf.j2
kubeinit/roles/kubeinit_bind/templates/named.conf.local.j2
kubeinit/roles/kubeinit_eks/tasks/50_post_deployment_tasks.yml
kubeinit/roles/kubeinit_haproxy/defaults/main.yml
kubeinit/roles/kubeinit_haproxy/tasks/main.yml
kubeinit/roles/kubeinit_haproxy/templates/haproxy.cfg.j2
kubeinit/roles/kubeinit_k8s/tasks/40_configure_worker_nodes.yml
kubeinit/roles/kubeinit_libvirt/tasks/10_cleanup.yml
kubeinit/roles/kubeinit_libvirt/templates/102-cloudinit-cloud.cfg.j2
kubeinit/roles/kubeinit_libvirt/templates/cluster-net.xml.j2
kubeinit/roles/kubeinit_okd/tasks/40_remove_bootstrap_node.yml
kubeinit/roles/kubeinit_registry/defaults/main.yml
kubeinit/roles/kubeinit_registry/tasks/10_configure.yml

feat: run apache http service from a container
feat: run bind9 DNS service from a container
feat: run local registry container with podman instead of docker
feat: run haproxy service from a container
fix: add missing cluster name to several places generating cluster FQDNs

Move services into containers

---

.github/workflows/release.yml
kubeinit/roles/kubeinit_haproxy/defaults/main.yml
kubeinit/roles/kubeinit_haproxy/tasks/main.yml
kubeinit/roles/kubeinit_registry/defaults/main.yml
kubeinit/roles/kubeinit_registry/tasks/00_install.yml
kubeinit/roles/kubeinit_registry/tasks/10_configure.yml

This commit removes the docker bits in the registry role
and some missing requisites for haproxy to be configured in
Ubuntu.

fix: remove docker and create haproxy files

---

kubeinit/roles/kubeinit_nfs/tasks/main.yml

This commit increases the timeout
for the NFS resources.

fix: allow requests to wait 1600s

---

kubeinit/roles/kubeinit_apache/tasks/main.yml
kubeinit/roles/kubeinit_bind/tasks/main.yml
kubeinit/roles/kubeinit_haproxy/tasks/main.yml
kubeinit/roles/kubeinit_registry/tasks/00_install.yml

This commit moves shell to command.

fix: move shell to command

---

kubeinit/roles/kubeinit_apache/tasks/main.yml
kubeinit/roles/kubeinit_bind/tasks/main.yml
kubeinit/roles/kubeinit_haproxy/tasks/main.yml
kubeinit/roles/kubeinit_libvirt/tasks/00_prepare.yml
kubeinit/roles/kubeinit_registry/tasks/00_install.yml

This commit moves the docker auth file to each
role using it.

fix: move docker pass to each role

---

kubeinit/playbooks/submariner-subctl-verify.yml
kubeinit/playbooks/submariner.yml
kubeinit/roles/kubeinit_submariner/tasks/00_broker_deployment.yml
kubeinit/roles/kubeinit_submariner/tasks/10_secondary_deployment.yml
kubeinit/roles/kubeinit_submariner/tasks/20_check_connection.yml
kubeinit/roles/kubeinit_submariner/tasks/30_subctl_verify.yml

This commit aligns submariner role to the pattern used in
all the other roles.

fix: make submariner playbooks aligned with the other roles

---

ci/run_submariner.sh
kubeinit/playbooks/submariner-subctl-verify.yml
kubeinit/playbooks/submariner.yml
kubeinit/roles/kubeinit_okd/tasks/10_configure_service_nodes.yml
kubeinit/roles/kubeinit_rke/tasks/20_configure_service_nodes.yml
kubeinit/roles/kubeinit_submariner/tasks/00_broker_deployment.yml
kubeinit/roles/kubeinit_submariner/tasks/10_secondary_deployment.yml
kubeinit/roles/kubeinit_submariner/tasks/20_check_connection.yml
kubeinit/roles/kubeinit_submariner/tasks/30_subctl_verify.yml

This commit adds the pending config details for
submariner.

fix: include pending submariner config

---

kubeinit/roles/kubeinit_submariner/tasks/00_broker_deployment.yml
kubeinit/roles/kubeinit_submariner/tasks/main.yml

Currently there is a bug when using
the make module as the submariner make
file has some errors captured by Ansible.

fix: adjust submariner make steps

---

ci/launch_e2e_periodic.py
ci/run_periodic.sh
kubeinit/README.md
kubeinit/roles/kubeinit_submariner/tasks/20_check_connection.yml
kubeinit/roles/kubeinit_submariner/tasks/30_subctl_verify.yml
kubeinit/roles/kubeinit_submariner/tasks/main.yml

This commit includes submariner in the periodic jobs.

feat: include  submariner in the periodic jobs

---

kubeinit/roles/kubeinit_okd/defaults/main.yml

This commit updates OKD to the latest version prior 4.7

feat: update OKD to latest 4.6

---

ci/launch_e2e_periodic.py

This commit fixes a nit in the ci scripts.

fix: nit fix in the ci script

---

kubeinit/roles/kubeinit_rke/defaults/main.yml
kubeinit/roles/kubeinit_rke/tasks/10_configure_common.yml

This commit fixes the YAML lint check.

fix: nit removal

---

kubeinit/roles/kubeinit_submariner/defaults/main.yml
kubeinit/roles/kubeinit_submariner/tasks/00_broker_deployment.yml
kubeinit/roles/kubeinit_submariner/tasks/10_secondary_deployment.yml

This commit allows to deploy submariner released versions.

feat: allow deploying released versions

---

ci/run_kubeinit.sh
kubeinit/roles/kubeinit_submariner/tasks/00_broker_deployment.yml

This commit removes some workarounds
for creating the submariner operator
images.

fix: remove the ignore errors in submariner

---

kubeinit/roles/kubeinit_bind/templates/named.conf.j2
kubeinit/roles/kubeinit_bind/templates/named.conf.local.j2
kubeinit/roles/kubeinit_cdk/tasks/30_post_service_config.yml
kubeinit/roles/kubeinit_eks/tasks/10_configure_service_nodes.yml
kubeinit/roles/kubeinit_eks/tasks/20_configure_common.yml
kubeinit/roles/kubeinit_k8s/tasks/10_configure_service_nodes.yml
kubeinit/roles/kubeinit_k8s/tasks/20_configure_common.yml
kubeinit/roles/kubeinit_libvirt/tasks/00_prepare.yml
kubeinit/roles/kubeinit_libvirt/tasks/20_ovn_install.yml
kubeinit/roles/kubeinit_libvirt/tasks/40_ovn_setup.yml
kubeinit/roles/kubeinit_libvirt/tasks/50_ovn_post_setup.yml
kubeinit/roles/kubeinit_libvirt/tasks/60_okd_deploy_nodes.yml
kubeinit/roles/kubeinit_libvirt/tasks/main.yml
kubeinit/roles/kubeinit_libvirt/templates/cluster-net.xml.j2
kubeinit/roles/kubeinit_nfs/defaults/main.yml
kubeinit/roles/kubeinit_nfs/tasks/main.yml
kubeinit/roles/kubeinit_okd/tasks/10_configure_service_nodes.yml
kubeinit/roles/kubeinit_okd/tasks/40_remove_bootstrap_node.yml
kubeinit/roles/kubeinit_okd/tasks/main.yml
kubeinit/roles/kubeinit_prepare/tasks/main.yml
kubeinit/roles/kubeinit_registry/defaults/main.yml
kubeinit/roles/kubeinit_rke/tasks/30_post_service_config.yml
kubeinit/roles/kubeinit_validations/tasks/10_libvirt_free_space.yml
kubeinit/roles/kubeinit_validations/tasks/20_libvirt_available_ram.yml
kubeinit/roles/kubeinit_validations/tasks/30_libvirt_check_cpu_cores.yml

This commit makes some initial changes in preparation for future
changes to how services are handled.  Now that services are all in
containers the process of moving those containers from a service
virtual machine into container pods can begin.

feat: reorganize and cleanup service nodes

---

kubeinit/hosts/cdk/inventory
kubeinit/hosts/eks/inventory
kubeinit/hosts/k8s/inventory
kubeinit/hosts/okd/inventory
kubeinit/hosts/rke/inventory
kubeinit/roles/kubeinit_haproxy/defaults/main.yml

fix: change haproxy stats port from 9090 to 9000
fix: add a second worker to each distro inventory

Small changes

---

ci/run_kubeinit.sh
ci/run_periodic.sh
ci/run_submariner.sh
kubeinit/roles/kubeinit_submariner/tasks/20_check_connection.yml

This commit increases the retry number for
checking that the submariner connection is up
and running.

fix: increase the timeout for checking the connection

---

kubeinit/hosts/common.yml
kubeinit/playbook.yml
kubeinit/roles/kubeinit_cdk/tasks/main.yml
kubeinit/roles/kubeinit_eks/tasks/main.yml
kubeinit/roles/kubeinit_k8s/tasks/main.yml
kubeinit/roles/kubeinit_libvirt/tasks/00_prepare.yml
kubeinit/roles/kubeinit_okd/tasks/main.yml
kubeinit/roles/kubeinit_prepare/tasks/main.yml
kubeinit/roles/kubeinit_rke/tasks/main.yml

This commit starts to pull the initial prepare phase tasks
together to provide more consistency in how facts are defined
and made available for the roles that depend on those facts.

feat: initial prepare role reorg and cleanup

---

kubeinit/roles/kubeinit_submariner/tasks/30_subctl_verify.yml

This commit removes an extra expace when executing subctl verify.

fix: remove extra spaces

---

ci/launch_e2e_periodic.py
ci/run_kubeinit.sh
ci/run_periodic.sh

This commit fixes the tag in the OVN job
for the periodic run.

fix: change the ovn periodic job tag

---

ci/ara.sh
ci/run_kubeinit.sh
ci/run_periodic.sh
ci/run_submariner.sh

This commit excludes ansible 4 from the CI.

fix: add pin to ansible <4

---

ci/install_gitlab_node.sh
ci/kubeinit_ci_utils.py
ci/launch_e2e_kubeinit.py
ci/launch_e2e_periodic.py
ci/launch_e2e_submariner.py
kubeinit/roles/kubeinit_prepare/tasks/00_set_facts.yml

This commit adds the hability to
upload the CI logs to GC instead
of pushing them to GH.

feat: include upload logs to CDN

---

ci/kubeinit_ci_utils.py

This commit fixes a path for reaching the periodic
jobs.

fix: update periodic job to the correct folder

---

Dockerfile
ci/install_gitlab_node.sh
ci/launch_e2e_kubeinit.py
ci/launch_e2e_periodic.py
ci/run_kubeinit.sh
ci/run_periodic.sh
ci/run_submariner.sh

This commit pushes a new job based on launching
the deployment command from a container.

feat: new CI job based on containers

---

ci/ara.sh

This commit fixes some internal CI links and content.

chore: fix internal strings

---

ci/ara.sh

This commit fixes the CI "about" description.

fix: update CI links

---

kubeinit/roles/kubeinit_prepare/tasks/prepare_localhost.yml

This commit comments some tasks
related to using services in
the bastion host, this feature is
not fully implemented yet.

fix: comment bastions tasks

---

kubeinit/README.md

This commit simplifies a little the readme content.

fix: update readme

---

kubeinit/roles/kubeinit_libvirt/defaults/main.yml

Removed Python 2 dependencies

---

kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_libvirt/tasks/10_cleanup.yml

This commit enables the Ubuntu release as
a variable.

fix: make the ubuntu distro as a variable

---

docs/src/usage.rst
kubeinit/roles/kubeinit_nexus/tasks/main.yml

This commit removes a hardwired IP
in the nexus service.

fix: do not use hardwire service IP

---

kubeinit/roles/kubeinit_prepare/tasks/prepare_podman.yml

This commit add no_log to the registry password management tasks.

fix: add nolog

---

kubeinit/roles/kubeinit_prepare/tasks/main.yml

This commit fixes the docs linter.
Authored-by: Glenn Marcy <homelab@glenn4u.com>

fix: fix docs linter

---

kubeinit/roles/kubeinit_eks/defaults/main.yml
kubeinit/roles/kubeinit_eks/tasks/10_configure_service_nodes.yml
kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_prepare/defaults/main.yml
kubeinit/roles/kubeinit_prepare/tasks/10_cleanup.yml
kubeinit/roles/kubeinit_prepare/tasks/50_ovn_post_setup.yml
kubeinit/roles/kubeinit_prepare/tasks/prepare_podman.yml
kubeinit/roles/kubeinit_registry/tasks/main.yml
kubeinit/roles/kubeinit_rke/defaults/main.yml
kubeinit/roles/kubeinit_rke/tasks/10_configure_common.yml
kubeinit/roles/kubeinit_rke/tasks/20_configure_service_nodes.yml
kubeinit/roles/kubeinit_rke/tasks/40_configure_control_plane_nodes.yml
kubeinit/roles/kubeinit_rke/tasks/50_configure_compute_nodes.yml
kubeinit/roles/kubeinit_rke/tasks/60_deploy_rke.yml
kubeinit/roles/kubeinit_services/tasks/prepare_credentials.yml

This commit addresses the issues with rke (and eks) created
when the prepare_credentials changes went in.

fix: add fixes for rke distro issues

---

ci/install_gitlab_node.sh
ci/run_kubeinit.sh
ci/run_periodic.sh
ci/run_submariner.sh

This commit uses the Ansible version
from the package repository instead of
PIP.

fix: remove ansible install from PIP

---

Dockerfile
ci/run_kubeinit.sh
ci/run_periodic.sh
ci/run_submariner.sh

This commit installs ansible from
dnf in the dockerfile and
makes sure we test the collections
versions in each PR.

fix: install ansible from dnf

---

.github/workflows/release.yml
ci/install_gitlab_node.sh
ci/run_kubeinit.sh
ci/run_periodic.sh
ci/run_submariner.sh
kubeinit/galaxy.yml
kubeinit/requirements.yml
tools/check_collection_deps.sh
tox.ini

This commit updates the collections
versions used in the project.

feat: bump collections versions

---

kubeinit/roles/kubeinit_bind/templates/create-external-ingress.sh.j2
kubeinit/roles/kubeinit_bind/templates/internals_db.j2
kubeinit/roles/kubeinit_bind/templates/internals_db.local.j2
kubeinit/roles/kubeinit_bind/templates/named.conf.local.j2
kubeinit/roles/kubeinit_cdk/tasks/60_deploy_cdk.yml
kubeinit/roles/kubeinit_libvirt/templates/101-cloudinit-hosts.tmpl.j2
kubeinit/roles/kubeinit_prepare/tasks/50_ovn_post_setup.yml

This commit upgrades the OKD version
to the latest available.

feat: bump OKD version to 4.7

---

kubeinit/roles/kubeinit_cdk/tasks/60_deploy_cdk.yml
kubeinit/roles/kubeinit_cdk/templates/bundle.yml.j2

This commit fixes the check to verify the etcd cluster is
up in CDK.

fix:  remove s from etcd cluster check

---

.github/ISSUE_TEMPLATE/bug_report.md
kubeinit/roles/kubeinit_prepare/tasks/20_ovn_install.yml

This commit starts the OVS/OVN services when using
Ubuntu/Debian hosts.

fix: start OVS/OVN services in Ubuntu HV

---

ci/run_kubeinit.sh
ci/run_periodic.sh
ci/run_submariner.sh
kubeinit/roles/kubeinit_prepare/tasks/10_cleanup.yml
kubeinit/roles/kubeinit_prepare/tasks/20_ovn_install.yml

This commit prunes all the OVS/OVN files.

fix: make sure all OVS files are removed

---

ci/run_kubeinit.sh
ci/run_periodic.sh
ci/run_submariner.sh
kubeinit/roles/kubeinit_libvirt/tasks/main.yml
kubeinit/roles/kubeinit_prepare/tasks/20_ovn_install.yml
kubeinit/roles/kubeinit_prepare/tasks/prepare_localhost.yml

This commit disables regenerating the
hosts keys if they exist.

fix: do not regenerate keys if they exist

---

ci/run_kubeinit.sh
ci/run_periodic.sh
ci/run_submariner.sh

This commit makes sure the podman
connections are cleaned in every run.

fix: cleanup podman connections in the CI

---

kubeinit/roles/kubeinit_okd/tasks/20_check_nodes_ready.yml
kubeinit/roles/kubeinit_okd/tasks/50_post_deployment_tasks.yml

This commit makes the scale down adjustments before the cluster
to converge.

fix: apply scale spec changes before converge

---

kubeinit/roles/kubeinit_okd/tasks/main.yml

Now we need to fix the etcd cluster before finishing
the bootstrap to complete. This commit removes the extra code.

fix: remove duplcicated call to 40_remove_bootstrap_node.yml

---

docs/src/roles/role-kubeinit_kid.rst
kubeinit/hosts/kid/README.md
kubeinit/hosts/kid/group_vars/all.yml
kubeinit/hosts/kid/inventory
kubeinit/playbooks/kid.yml
kubeinit/roles/kubeinit_kid/README.md
kubeinit/roles/kubeinit_kid/defaults/main.yml
kubeinit/roles/kubeinit_kid/handlers/main.yml
kubeinit/roles/kubeinit_kid/meta/main.yml
kubeinit/roles/kubeinit_kid/molecule/default/converge.yml
kubeinit/roles/kubeinit_kid/molecule/default/molecule.yml
kubeinit/roles/kubeinit_kid/molecule/default/verify.yml
kubeinit/roles/kubeinit_kid/tasks/00_bounce_packages.yml
kubeinit/roles/kubeinit_kid/tasks/10_configure_common.yml
kubeinit/roles/kubeinit_kid/tasks/30_post_service_config.yml
kubeinit/roles/kubeinit_kid/tasks/40_configure_control_plane_nodes.yml
kubeinit/roles/kubeinit_kid/tasks/50_configure_compute_nodes.yml
kubeinit/roles/kubeinit_kid/tasks/60_deploy_kid.yml
kubeinit/roles/kubeinit_kid/tasks/70_post_deployment_services_tasks.yml
kubeinit/roles/kubeinit_kid/tasks/configure_service_nodes.yml
kubeinit/roles/kubeinit_kid/tasks/main.yml
kubeinit/roles/kubeinit_kid/tasks/prepare_cluster.yml
kubeinit/roles/kubeinit_kid/vars/main.yml
kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_libvirt/tasks/60_deploy_debian_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/main.yml
kubeinit/roles/kubeinit_libvirt/templates/debian-network-config-enp1s0.j2

This commit includes the first milestone
to create a truly FOSS k8s distribution.

feat: include initial KID automation

---

ci/launch_e2e_periodic.py
kubeinit/README.md

This commit includes the KID periodic
jobs.

feat: include KID peridoc jobs

---

kubeinit/hosts/cdk/inventory
kubeinit/hosts/eks/inventory
kubeinit/hosts/k8s/inventory
kubeinit/hosts/kid/inventory
kubeinit/hosts/okd/inventory
kubeinit/hosts/rke/inventory
kubeinit/roles/kubeinit_cdk/defaults/main.yml
kubeinit/roles/kubeinit_cdk/tasks/70_post_deployment_services_tasks.yml
kubeinit/roles/kubeinit_eks/defaults/main.yml
kubeinit/roles/kubeinit_eks/tasks/50_post_deployment_tasks.yml
kubeinit/roles/kubeinit_k8s/defaults/main.yml
kubeinit/roles/kubeinit_k8s/tasks/50_post_deployment_tasks.yml
kubeinit/roles/kubeinit_kid/defaults/main.yml
kubeinit/roles/kubeinit_libvirt/tasks/main.yml
kubeinit/roles/kubeinit_nfs/defaults/main.yml
kubeinit/roles/kubeinit_nfs/tasks/main.yml
kubeinit/roles/kubeinit_okd/defaults/main.yml
kubeinit/roles/kubeinit_okd/tasks/50_post_deployment_tasks.yml
kubeinit/roles/kubeinit_okd/tasks/configure_service_nodes.yml
kubeinit/roles/kubeinit_okd/tasks/prepare_localhost.yml
kubeinit/roles/kubeinit_rke/defaults/main.yml
kubeinit/roles/kubeinit_rke/tasks/70_post_deployment_services_tasks.yml
kubeinit/roles/kubeinit_services/tasks/prepare_credentials.yml
kubeinit/roles/kubeinit_services/tasks/start_services_containers.yml

This commit moves the distro check to the
guest OS check when installing services.

fix: move distro check to guest os check

---

kubeinit/roles/kubeinit_kid/defaults/main.yml

This commit removes some packages not available anymore
in Debian.

fix: adjust KID packages

---

.github/workflows/distro_test.yml
.github/workflows/molecule.yml

This commit try to run a partial distro eployment
in github actions.

feat: include a distro deployment in GA

---

.github/workflows/distro_test.yml
Dockerfile
docs/src/usage.rst
kubeinit/README.md

This commit adds running the playbook from
a container so we test the build and reqs.
install.

ci: run deployment from container

---

ci/run_kubeinit.sh

This commit makes explicit
running the automation as root
from a container.

ci: run from a container as root

---

.github/workflows/distro_test.yml
kubeinit/roles/kubeinit_libvirt/tasks/10_cleanup.yml
kubeinit/roles/kubeinit_libvirt/tasks/deploy_network.yml
kubeinit/roles/kubeinit_libvirt/tasks/download_cloud_images.yml
kubeinit/roles/kubeinit_libvirt/tasks/main.yml

This commit moves forward the upstream
GitHub actions check, just after the
services are configured.

ci: move GA check after preparing services

---

ci/launch_e2e.py
periodic_jobs.md

This commit fixes a nit in the periodic job
page.

ci: fix nit

---

.github/workflows/render_periodic_jobs_status_page.yml
ci/periodic_jobs.md.j2

This commit updates the commit title
and removes some unneeded extra lines
in the jinja template.

ci: remove extra lines and update commit message

---

ci/launch_e2e.py
ci/periodic_jobs.md.j2

This commit includes some minor cosmetic
changes to the periodic jobs status page.

ci: minor changes

---

ci/kubeinit_ci_utils.py
ci/launch_e2e.py
ci/render_periodic_jobs_page.py

This commit allows to split the periodic job per distro.

ci: allow splitting the period job per distro

---

.gitlab-ci.yml
ci/kubeinit_ci_utils.py
ci/launch_e2e.py
ci/run_e2e.sh

This commit reduces the amount of
jobs available in the periodic table.

ci: reduce the amount of jobs

---

ci/ara.sh
ci/kubeinit_ci_utils.py
ci/launch_e2e.py

This commit allows to pass jobs labels to the periodic jobs.

ci: allow run specific labels in periodic jobs

---

ci/kubeinit_ci_utils.py
ci/launch_e2e.py
ci/run_e2e.sh

This commit adjusts the regex to allow
0 compute deployments.

ci: allow 0 computes deployment

---

ci/run_e2e.sh

This commit balances the nodes
in the 3 nodes cluster so it
have enough resources.

ci: balance CI cluster load

---

ci/ara.sh
ci/install_gitlab_node.sh
ci/kubeinit_ci_utils.py
ci/launch_e2e.py
ci/run_e2e.sh

This commit adds some minor
improvements to the CI.

ci: minor fixes

---

Dockerfile
ci/ara.sh
ci/install_gitlab_node.sh
ci/run_e2e.sh

Currently ARA runs in a sqlite DB,
due to the size of the playbooks
we are starting to have locks blocking
rendering the results.

ci: run ARA from a podman container

---

ci/kubeinit_ci_utils.py
ci/launch_e2e.py
ci/launch_e2e.sh
ci/launch_e2e_ara.sh

This commit organizes better
the CI scripts and adds an
option to test a set of random
distros from the allowed scenarios.

ci: reorg CI files

---

ci/launch_e2e_ara.sh

This commit fixes a regex error in the job
result about page.

ci: fix regex

---

ci/install_gitlab_node.sh
ci/launch_e2e.sh
ci/launch_e2e_ara.sh

This commit makes ara to log in
the server IP instead of localhost.

ci: log to server IP

---

ci/launch_e2e_ara.sh

This commit allow replacing empty urls
for the main CI jobs page.

ci: allow replace empty url

---

ci/launch_e2e.sh

This commit allows to record relevant
files in the CI job execution.

ci: record relevant files

---

.github/workflows/docs_build_pr.yml
.github/workflows/release.yml
ci/launch_e2e.sh

This commit adds additional
information to the deployment
job page.

ci: add extra information to the CI job page

---

ci/kubeinit_ci_utils.py
ci/launch_e2e.sh

This commit increases the numbers
of running job from 3 to 4.

ci: run 4 jobs instead of 3

---

ci/kubeinit_ci_utils.py
ci/periodic_jobs.md.j2
ci/render_periodic_jobs_page.py

This commit includes the date
information in the job status pages.

ci: include date in jobs

---

ci/kubeinit_ci_utils.py

This commit fixes a nit in the job id rendering,

ci: fix job id index

---

ci/launch_e2e.py

This commit makes the CI job to fail
when the Ansible playbook fails.

ci: fail when the playbooks fails

---

.github/workflows/container_image.yml
.github/workflows/distro_test.yml
.github/workflows/docs_build_pr.yml
.github/workflows/linters.yml
.github/workflows/molecule.yml
.github/workflows/release.yml
.github/workflows/units.yml
_skeleton_role_/meta/main.yml.j2
ci/launch_e2e.sh
kubeinit/README.md
kubeinit/roles/kubeinit_apache/meta/main.yml
kubeinit/roles/kubeinit_bind/meta/main.yml
kubeinit/roles/kubeinit_cdk/meta/main.yml
kubeinit/roles/kubeinit_dnsmasq/meta/main.yml
kubeinit/roles/kubeinit_eks/meta/main.yml
kubeinit/roles/kubeinit_haproxy/meta/main.yml
kubeinit/roles/kubeinit_k8s/meta/main.yml
kubeinit/roles/kubeinit_kid/meta/main.yml
kubeinit/roles/kubeinit_kubevirt/meta/main.yml
kubeinit/roles/kubeinit_libvirt/meta/main.yml
kubeinit/roles/kubeinit_nexus/meta/main.yml
kubeinit/roles/kubeinit_nfs/meta/main.yml
kubeinit/roles/kubeinit_okd/meta/main.yml
kubeinit/roles/kubeinit_prepare/meta/main.yml
kubeinit/roles/kubeinit_registry/meta/main.yml
kubeinit/roles/kubeinit_rke/meta/main.yml
kubeinit/roles/kubeinit_services/meta/main.yml
kubeinit/roles/kubeinit_submariner/meta/main.yml
kubeinit/roles/kubeinit_validations/meta/main.yml

This commit allows to run the GitHub
jobs periodically to have a better
visibility if something gets updated.

ci: make jobs run periodically

---

.github/workflows/distro_test.yml
.github/workflows/docs_build_pr.yml
.github/workflows/release.yml
kubeinit/roles/kubeinit_okd/tasks/main.yml
kubeinit/roles/kubeinit_validations/tasks/10_libvirt_free_space.yml
kubeinit/roles/kubeinit_validations/tasks/20_libvirt_available_ram.yml
kubeinit/roles/kubeinit_validations/tasks/30_libvirt_check_cpu_cores.yml

Also small fix to OKD wait-for bootstrap-complete task

ci: add var to ignore validation checks

---

ci/launch_e2e.py

This commit includes the repo name in the periodic jobs
build.

ci: include repo name in periodic jobs

---

ci/launch_e2e.py

This commit calls correctly
the get issue method when
recording the job result.

ci: call the get issue method

---

kubeinit/roles/kubeinit_okd/tasks/main.yml

This commit adds a new line so we wait
correctly for the cluster to converge.

fix: add new line waiting for converge

---

docs/src/usage.rst
kubeinit/README.md

This commit includes information about how to build and
install the collection.
Closes: #495

docs: include building and installing the collection

---

docs/src/usage.rst

This commit updates the way to clean up the hypervisors.
Closes: #473

docs: update clean tasks

---

agent/setup.py
kubeinit/galaxy.yml
ui/app/version.py
ui/package.json

This commit releases a new version of
Kubeinit including a major refactor and
architectural changes.
Thanks to all Kubeinit's contributors!!!

feat: release 2.0.0

---

ci/check_labels_consistency.py
ci/kubeinit_ci_logs.html.j2
ci/kubeinit_ci_utils.py
ci/launch_e2e.py
ci/launch_e2e.sh
ci/periodic_jobs.md.j2
ci/render_periodic_jobs_page.py

This commit removes from the CI all the
references to the virtual machine
hosting the deployment services as they are
now containerized in the bastion host.

ci: remove virtual services definition

---

docs/src/static/css/custom.css
docs/src/supporters.rst
kubeinit/README.md

This commit fixes some styling issues
after having all the required images
and content.

docs: fix supporters styles

---

ci/install_gitlab_node.sh
ci/launch_e2e.sh

This commit removes some unneeded packages
in the install script as they will
be installed from the deployment command.

ci: cleanup install script

---

ci/launch_e2e.sh

This commit includes a feature to stop the CI job
after the cluster is deployed for debugging purposes.

ci: include a waitfordebug label

---

kubeinit/roles/kubeinit_okd/defaults/main.yml

This commit updates the OKD version
that is deployed by default.

feat: update OKD version

---

docs/src/architecture.rst
docs/src/usage.rst

This commit adds documentation about the services pod
and the Kubeinit spec.
Closes: #555
Closes: #331

docs: include docs for the services pod and spec

---

docs/src/usage.rst

This commit sorts better the current usage documentation.

docs: organize better the usage documentation

---

docs/src/usage.rst

This commit sorts the titles consistently.

docs: sorting titles

---

docs/src/_templates/layout.html
docs/src/conf.py
docs/src/index.rst

This commit includes the GH link in the
docs pages.

docs: include GitHub docs in the code

---

docs/src/architecture.rst
docs/src/conf.py
docs/src/contributing.rst
docs/src/index.rst
docs/src/installation.rst
docs/src/usage.rst

This commit refactors the docs
to have a more streamlined view
of the content we will like to describe.

docs: refator docs

---

kubeinit/group_vars/all.yml
kubeinit/playbook.yml
kubeinit/roles/kubeinit_bind/templates/create-external-ingress.sh.j2
kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_libvirt/tasks/60_create_cloud_user.yml
kubeinit/roles/kubeinit_libvirt/tasks/70_check_nodes_up.yml
kubeinit/roles/kubeinit_prepare/tasks/gather_host_facts.yml
kubeinit/roles/kubeinit_prepare/tasks/main.yml
kubeinit/roles/kubeinit_rke/templates/cluster.yml.j2
kubeinit/roles/kubeinit_services/tasks/00_create_service_pod.yml
kubeinit/roles/kubeinit_services/tasks/create_provision_container.yml

This commit adds the option to use an ssh keytype other than the default rsa.

feat: added variable for selecting the ssh keytype

---

kubeinit/README.md

Fix the instructions, so copy-paste is possible.
write out the command options

docs: fix instructions

---

.github/workflows/distro_test.yml
ci/kubeinit_ci_logs.html.j2
ci/kubeinit_ci_utils.py
ci/launch_e2e.sh
kubeinit/inventory
kubeinit/roles/kubeinit_bind/defaults/main.yml
kubeinit/roles/kubeinit_bind/templates/named.conf.local.j2
kubeinit/roles/kubeinit_okd/defaults/main.yml
kubeinit/roles/kubeinit_okd/tasks/post_deployment_tasks.yml
kubeinit/roles/kubeinit_okd/templates/install-config.yaml.j2
kubeinit/roles/kubeinit_prepare/tasks/gather_kubeinit_facts.yml
kubeinit/roles/kubeinit_rke/tasks/post_deployment_tasks.yml
kubeinit/roles/kubeinit_submariner/defaults/main.yml
kubeinit/roles/kubeinit_submariner/tasks/00_broker_deployment.yml
kubeinit/roles/kubeinit_submariner/tasks/10_secondary_deployment.yml
kubeinit/roles/kubeinit_submariner/tasks/20_check_connection.yml
kubeinit/roles/kubeinit_submariner/tasks/30_subctl_verify.yml
kubeinit/roles/kubeinit_submariner/tasks/main.yml

This commit enables the submariner
deployment in a multicluster environment.

feat: include submariner deployments

---

ci/kubeinit_ci_utils.py

This commit includes a timeout to fetch the
CI results page.

fix: add a blocking timeout to get results

---

ci/kubeinit_ci_logs.html.j2
ci/kubeinit_ci_utils.py

This commit includes the internal job link
in the CI dashboard.

ci: add internal job link in the CI dashboard

---

ci/kubeinit_ci_logs.html.j2
ci/kubeinit_ci_utils.py

This commit includes the whole URL when opening the
internal job.

ci: use full URL in the job id

---

ci/kubeinit_ci_logs.html.j2

This commit sort and filter jobs in the CI
dashboard depending on the job type.

ci: sort and filter jobs

---

docs/src/README.md
docs/src/usage.rst

addendum to #568, with the requested changes
Sorry for the wait

docs: finalize fix instructions

---

agent/setup.py
kubeinit/galaxy.yml
ui/app/version.py
ui/package.json

This commit releases the latest changes
from the main development branch.

feat: release 2.0.1

---

.github/workflows/container_image.yml
.github/workflows/distro_test.yml
.github/workflows/docs_build.yml
.github/workflows/linters.yml
.github/workflows/molecule.yml
.github/workflows/release.yml
.github/workflows/render_periodic_jobs_status_page.yml
.github/workflows/stale.yml
.github/workflows/units.yml
Dockerfile
kubeinit/galaxy.yml
kubeinit/requirements.yml

This commit tests Ansible 5 in the release
script.

ci: update to Ansible 5

---

.github/workflows/distro_test.yml
kubeinit/roles/kubeinit_setup/tasks/gather_setup_facts.yml
kubeinit/roles/kubeinit_setup/tasks/prepare_hypervisors.yml
kubeinit/roles/kubeinit_setup/tasks/setup_ansible_host.yml
kubeinit/setup-playbook.yml

Tested setup against several newly installed minimal hosts and found a few nits that needed to be addressed

ci: fix setup of minimum req hosts

---

docs/src/images/plantuml/.gitignore
docs/src/images/plantuml/ansible_deployment_sequence_diagram.plantuml
docs/src/images/plantuml/github_workflow.plantuml

This commit adds anoter iteration to the
sequence diagram to describe how the deployments work.

docs: update ansible workflow diagram

---

ci/install_gitlab_node.sh
ci/launch_e2e.py
kubeinit/galaxy.yml
kubeinit/requirements.yml
kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_prepare/tasks/gather_kubeinit_facts.yml
kubeinit/roles/kubeinit_services/tasks/create_provision_container.yml

This commit adds the latest LTS version to be used in all distros.

fix: use Ubuntu LTS for all Ubuntu based distros

---

ci/ansible/group_vars/all.yml
ci/ansible/group_vars/kubeinit_env.yml
ci/ansible/group_vars/kubeinit_secrets.yml
kubeinit/group_vars/all.yml
kubeinit/group_vars/kubeinit_env.yml
kubeinit/group_vars/kubeinit_secrets.yml
kubeinit/inventory
kubeinit/playbook.yml
kubeinit/roles/kubeinit_libvirt/tasks/cleanup_libvirt.yml
kubeinit/roles/kubeinit_libvirt/tasks/create_network.yml
kubeinit/roles/kubeinit_nexus/tasks/main.yml
kubeinit/roles/kubeinit_okd/defaults/main.yml
kubeinit/roles/kubeinit_okd/tasks/prepare_cluster.yml
kubeinit/roles/kubeinit_prepare/tasks/create_host_ssh_config.yml
kubeinit/roles/kubeinit_prepare/tasks/gather_host_facts.yml
kubeinit/roles/kubeinit_prepare/tasks/gather_kubeinit_facts.yml
kubeinit/roles/kubeinit_prepare/tasks/gather_kubeinit_secrets.yml
kubeinit/roles/kubeinit_prepare/tasks/main.yml
kubeinit/roles/kubeinit_prepare/tasks/prepare_groups.yml
kubeinit/roles/kubeinit_prepare/tasks/prepare_podman.yml
kubeinit/roles/kubeinit_prepare/templates/ssh-config.j2
kubeinit/roles/kubeinit_services/tasks/prepare_credentials.yml
kubeinit/roles/kubeinit_setup/tasks/gather_host_facts.yml
kubeinit/roles/kubeinit_setup/tasks/gather_setup_facts.yml
kubeinit/roles/kubeinit_setup/tasks/prepare_environment.yml
kubeinit/roles/kubeinit_setup/tasks/prepare_hypervisors.yml
kubeinit/roles/kubeinit_setup/tasks/setup_ansible_host.yml

Updates focused on vars for environment, secrets and network.  These changes will not support docker password environment variables with the password as the value.  Compatibility for that will be added to the CI as needed.  Passwords should be kept in files and secrets instead.

refactor: more group_vars updates

---

.github/workflows/gitlab_ci_trigger.yml
.gitlab-ci.yml
ci/gitlab_ci_trigger.sh
ci/gitlab_ci_trigger_test.sh
ci/yamlfind.sh

This commit adds an initial CI trigger
that allows to test CI changes in the PRs.

ci: include initial ci trigger

---

agent/requirements.txt
ci/ansible/roles/kubeinit_ci/tasks/main.yml
ci/install_gitlab_node.sh
ci/kubeinit_ci_utils.py
ci/launch_e2e.py
ci/launch_e2e.sh
ci/launch_e2e_ara.sh
ci/render_periodic_jobs_page.py
test-requirements.txt

This commit includes the Backblaze b2 backend for the CI
logs results.

feat: include Backblaze b2 file uploads

---

ci/install_gitlab_node.sh
ci/launch_e2e_ara.sh

This commit includes the new CI URL
in the ARA pages.

ci: include the new url for ara links

---

ci/kubeinit_ci_utils.py
ci/launch_e2e.py

This commit cleans up CI files older than 10 days.

ci: clean older ci files

---

.github/workflows/docs_build.yml
docs/src/_exts/autoyaml.py
docs/src/_exts/ghcontributors.py
docs/src/conf.py
docs/src/usage.rst
kubeinit/group_vars/kubeinit_env.yml

This commit enables the usage of comments redenred
automatically in the docs.

docs: include comments from code in the docs

---

docs/src/conf.py
docs/src/usage.rst
kubeinit/group_vars/kubeinit_secrets.yml

This commit includes the placeholder
to document the secrets.

docs: include docs placeholder for secrets

---

.gitlab-ci.yml
ci/gitlab_ci_trigger.sh
ci/gitlab_ci_trigger_test.sh
ci/launch_e2e.py
ci/launch_e2e.sh

This commit includes the bridge between the Gitlab
CI trigger and the current CI scripts.

ci: include the new bash script trigger in the CI

---

ci/launch_e2e.py

This commit splits the process of uploading the
CI logs file from the deployment time.

ci: move logs upload from deployment time

---

ci/launch_e2e.py

This commit fixes an error
in the string interpolation.

ci: correct string interpolation

---

ci/kubeinit_ci_utils.py

This commit ignores the removal of
old periodic job files, and the main index.
There should be only removed PR job files
older than 10 days.

ci: ignore removing periodic job files

---

ci/kubeinit_ci_utils.py

This commit includes the file name
to be deleted when is older than 10 days.

ci: print files to be deleted

---

.github/workflows/clean_b2_old_files.yml
.github/workflows/release.yml
.github/workflows/render_periodic_jobs_status_page.yml
.github/workflows/stale.yml

This commit makes some updates
in the jobs namings to make them
consistent.

ci: update jobs names

---

ci/kubeinit_ci_utils.py
ci/launch_e2e.py

This commit includes the cluster type info, when returning
the labels to be executed.

ci: include cluster_type

---

ci/launch_e2e.sh
kubeinit/roles/kubeinit_okd/defaults/main.yml
kubeinit/roles/kubeinit_okd/tasks/prepare_cluster.yml

This commit upgrades the version that is deployed by
default too OKD 4.10

feat: upgrade OKD to latest 4.9

---

agent/setup.py
kubeinit/galaxy.yml
ui/app/version.py
ui/package.json

This commit releases a new version of KubeInit.

chore: release 2.1.0

---

ci/launch_e2e.py

This commit fixes the current CI issues.

fix: CI is not rendering logs

---

ui/README.md
ui/app/__init__.py
ui/app/base/routes.py
ui/app/base/templates/base-site-fullscreen.html
ui/app/base/templates/base-site.html
ui/app/base/templates/site_template/scripts.html
ui/db_clear.py
ui/db_mock.py
ui/models/__init__.py
ui/requirements.txt

This commit includes the initial model
to include datacenter operation in the
web interface.

feat: include datacenter DB model

---

kubeinit/group_vars/kubeinit_defaults.yml
kubeinit/roles/kubeinit_apps/tasks/sampleapp.yml
kubeinit/roles/kubeinit_apps/templates/sampleapp.yml.j2
kubeinit/roles/kubeinit_cdk/tasks/post_deployment_tasks.yml
kubeinit/roles/kubeinit_cdk/templates/bundle.yml.j2
kubeinit/roles/kubeinit_eks/tasks/post_deployment_tasks.yml
kubeinit/roles/kubeinit_k8s/tasks/post_deployment_tasks.yml
kubeinit/roles/kubeinit_kid/tasks/post_deployment_tasks.yml
kubeinit/roles/kubeinit_okd/tasks/post_deployment_tasks.yml
kubeinit/roles/kubeinit_rke/tasks/post_deployment_tasks.yml

This commit fixes the apps demo role after deploying OKD.

fix: check OKD connectivity

---

ci/launch_e2e.sh
kubeinit/roles/kubeinit_apps/templates/sampleapp.yml.j2
kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_libvirt/tasks/70_check_nodes_up.yml
kubeinit/roles/kubeinit_libvirt/tasks/deploy_centos_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/deploy_debian_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/deploy_ubuntu_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/main.yml

This commit fixes the connectivity issue blocking
the connection to the first controller.

fix: check connectivity issue

---

kubeinit/roles/kubeinit_apps/templates/sampleapp.yml.j2

This commit makes pulling from quay
the sampleapp.

ci: pull from quay the sampleapp

---

ci/gitlab_ci_trigger.sh
ci/install_gitlab_node.sh

This commit removes some unneeded steps in
the GitLab trigger. No extra install step
is required anymore.

ci: remove unneeded steps

---

ci/launch_e2e.sh
kubeinit/roles/kubeinit_k8s/tasks/main.yml
kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_libvirt/tasks/deploy_windows_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/download_cloud_images.yml
kubeinit/roles/kubeinit_libvirt/templates/autounattend.xml.j2
kubeinit/roles/kubeinit_libvirt/templates/windows_setup.ps1.j2
kubeinit/roles/kubeinit_prepare/tasks/gather_kubeinit_facts.yml

This feature adds Windows workloads
to Kubeinit clusters.

feat: new Windows compute nodes

---

.ansible-lint
.github/workflows/distro_test.yml
Dockerfile
kubeinit/roles/kubeinit_apps/defaults/main.yml
kubeinit/roles/kubeinit_apps/tasks/sampleapp.yml
kubeinit/roles/kubeinit_apps/templates/sampleapp.yml.j2
kubeinit/roles/kubeinit_cdk/tasks/post_configure_guest.yml
kubeinit/roles/kubeinit_eks/tasks/post_configure_guest.yml
kubeinit/roles/kubeinit_k8s/defaults/main.yml
kubeinit/roles/kubeinit_k8s/tasks/post_configure_guest.yml
kubeinit/roles/kubeinit_prepare/tasks/prepare_podman.yml
kubeinit/roles/kubeinit_setup/tasks/prepare_environment.yml

This commit fixes packages inconsistencies across
the different Linux distributions.

fix: update containers repositories

---

kubeinit/galaxy.yml
kubeinit/requirements.yml
kubeinit/roles/kubeinit_k8s/tasks/main.yml
kubeinit/roles/kubeinit_libvirt/tasks/deploy_windows_guest.yml
kubeinit/roles/kubeinit_libvirt/templates/authorized_keys.j2
kubeinit/roles/kubeinit_libvirt/templates/autounattend.xml.j2
kubeinit/roles/kubeinit_libvirt/templates/install-openssh.ps1.j2

This commit allows to connect to Windows compute nodes in
the deployment of a mixed OS Kubeinit deployment.

feat: allow to connect to Windows compute nodes

---

ci/launch_e2e.sh
kubeinit/roles/kubeinit_apps/tasks/main.yml
kubeinit/roles/kubeinit_apps/tasks/win_sampleapp.yml
kubeinit/roles/kubeinit_apps/templates/sampleapp.yml.j2
kubeinit/roles/kubeinit_apps/templates/win_sampleapp.yml.j2
kubeinit/roles/kubeinit_k8s/defaults/main.yml
kubeinit/roles/kubeinit_k8s/tasks/main.yml
kubeinit/roles/kubeinit_k8s/templates/kube-flannel.yml.j2
kubeinit/roles/kubeinit_libvirt/tasks/deploy_windows_guest.yml
kubeinit/roles/kubeinit_libvirt/templates/Install-Containerd.ps1.j2
kubeinit/roles/kubeinit_libvirt/templates/PrepareFlannel.ps1.j2
kubeinit/roles/kubeinit_libvirt/templates/PrepareNode.ps1.j2
kubeinit/roles/kubeinit_libvirt/templates/PrepareRequirements.ps1.j2
kubeinit/roles/kubeinit_libvirt/templates/SetNet.ps1.j2
kubeinit/roles/kubeinit_libvirt/templates/autounattend.xml.j2

This commit executes kubelet in the Windows compute
nodes to add them to the control plane.

feat: run Kubelet in the Windows computes

---

.github/workflows/distro_test.yml
ansible.cfg
ci/ansible/roles/kubeinit_ci/tasks/gather_ci_facts.yml
ci/launch_e2e.sh
kubeinit/group_vars/kubeinit_cluster.yml
kubeinit/group_vars/kubeinit_defaults.yml
kubeinit/group_vars/kubeinit_network.yml
kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_openshift/tasks/main.yml
kubeinit/roles/kubeinit_prepare/tasks/build_hypervisors_group.yml
kubeinit/roles/kubeinit_prepare/tasks/gather_kubeinit_facts.yml
kubeinit/roles/kubeinit_prepare/tasks/main.yml
kubeinit/roles/kubeinit_prepare/tasks/prepare_groups.yml
kubeinit/roles/kubeinit_setup/tasks/gather_setup_facts.yml

testing new extra_nodes_spec handling

fixes for carlos/wansi

---

.github/workflows/distro_test.yml

This commit fixes the quotes order to have expended correctly the hostname
variable.

fix: invert quoting

---

ci/check_labels_consistency.py
ci/launch_e2e.sh
kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_libvirt/tasks/deploy_centos_guest.yml
kubeinit/roles/kubeinit_openstack/defaults/main.yml
kubeinit/roles/kubeinit_openstack/tasks/main.yml
kubeinit/roles/kubeinit_openstack/tasks/podified_controlplane.yml
kubeinit/roles/kubeinit_openstack/tasks/standalone_compute.yml
kubeinit/roles/kubeinit_openstack/tasks/standalone_tripleo.yml

This commit includes a TripleO
standalone deployment in the
recently added Nova compute nodes.

feat: include TripleO standalone

---

.github/workflows/check_package_build.yml
Dockerfile
ci/check_open_build_service.py
kubeinit/README.md
kubeinit/roles/kubeinit_eks/tasks/post_configure_guest.yml
kubeinit/roles/kubeinit_k8s/tasks/post_configure_guest.yml

This commit moves the pending references of
CentOS Stream 8 to 9.

feat: move to Stream9

---

ci/install_gitlab_node.sh
ci/launch_e2e.sh
kubeinit/group_vars/all.yml
kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_openstack/defaults/main.yml
kubeinit/roles/kubeinit_openstack/tasks/main.yml
kubeinit/roles/kubeinit_openstack/tasks/standalone_tripleo.yml

This commit makes sure the network
hiccup when installing TripleO
is checked to avoid failures.

fix: check network hiccup when deploying OOO

---

.github/workflows/docs_build.yml

This commit adds a pin to
ansible-playbook-grapher for
debugging.

fix: pin ansible-playbook-grapher

---

.github/workflows/docs_build.yml

This commit removes the pin version of
ansible-playbook-grapher

fix: remove ansible-playbook-grapher pinned version

---

kubeinit/roles/kubeinit_openstack/tasks/prepare_auth.yml
kubeinit/roles/kubeinit_openstack/tasks/seed_deployment.yml

This commit includes the initial tasks used
for seeding the cluster's resources deployed
on an OpenStack cloud.

feat: include initial tasks for OS resources

---

ci/launch_e2e.py

This commit updates the issue to log the periodic CI results.

chore: update periodic issue log

---

ci/install_gitlab_node.sh

This commit allows to run the GitLab
install script locally without GitLab.

ci: allow local install

---

Dockerfile
ci/kubeinit_ci_utils.py
ci/launch_e2e.sh
kubeinit/roles/kubeinit_eks/tasks/post_configure_guest.yml
kubeinit/roles/kubeinit_k8s/tasks/post_configure_guest.yml
kubeinit/roles/kubeinit_services/defaults/main.yml
kubeinit/roles/kubeinit_services/tasks/create_provision_container.yml
kubeinit/roles/kubeinit_services/tasks/prepare_credentials.yml

This commit includes default variable to set up the services container image.

fix: allow using CentOS stream 9 for the services deployments

---

.github/workflows/check_package_build.yml
ci/check_open_build_service.py

This commit includes both the user and password
to check the packages build status.

ci: add user and pasword for OBS

---

tox.ini

This commit allows external commands in tox.

ci: move whish to allow in tox

---

.github/workflows/linters.yml
.github/workflows/molecule.yml
.github/workflows/quay_mirror.yml
.github/workflows/release.yml
.github/workflows/units.yml
_skeleton_role_/molecule/default/molecule.yml
ci/ansible/roles/kubeinit_ci/tasks/main.yml
ci/container_sync.sh
ci/launch_e2e.sh
kubeinit/README.md
kubeinit/roles/kubeinit_apache/tasks/main.yml
kubeinit/roles/kubeinit_apps/templates/sampleapp.yml.j2
kubeinit/roles/kubeinit_bind/tasks/main.yml
kubeinit/roles/kubeinit_bind/templates/create-external-ingress.sh.j2
kubeinit/roles/kubeinit_haproxy/tasks/main.yml
kubeinit/roles/kubeinit_nexus/tasks/main.yml
kubeinit/roles/kubeinit_nodered/molecule/default/molecule.yml
kubeinit/roles/kubeinit_ooonextgen/molecule/default/molecule.yml
kubeinit/roles/kubeinit_openstack/molecule/default/molecule.yml
kubeinit/roles/kubeinit_openwhisk/molecule/default/molecule.yml
kubeinit/roles/kubeinit_registry/tasks/main.yml
kubeinit/roles/kubeinit_services/tasks/create_provision_container.yml

This commit fixes the references to container images hosted in docker.io that might hit limit-rate issues.

fix: mirror correctly images from docker.io to quay

---

agent/setup.py
kubeinit/galaxy.yml
ui/app/version.py
ui/package.json

This commit releases a new Kubeinit 2.2.0
version.

feat: release 2.2.0

---

ci/container_sync.sh
kubeinit/roles/kubeinit_apps/templates/sampleapp.yml.j2

The sample app runs nginx-unprivileged.

fix: include nginx-unprivileged

---

ci/container_sync.sh
ci/install_gitlab_node.sh
kubeinit/roles/kubeinit_apps/tasks/coco.yml
kubeinit/roles/kubeinit_apps/tasks/main.yml
kubeinit/roles/kubeinit_apps/templates/coco_workload.j2

This patch includes the initial support for adding Confidential Containers in the deployments.

feat: add Confidential Containers support

---

kubeinit/roles/kubeinit_libvirt/tasks/deploy_centos_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/deploy_debian_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/deploy_ubuntu_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/main.yml

This commit fix a few linter issues.

chore: fix lint issues

---

.github/workflows/docs_build.yml
kubeinit/roles/kubeinit_k8s/tasks/post_configure_guest.yml
kubeinit/roles/kubeinit_submariner/tasks/00_broker_deployment.yml
kubeinit/roles/kubeinit_submariner/tasks/10_secondary_deployment.yml

This commit fixes the current lint errors
and includes the missing dependencies for
imagemagick.

ci: linters fix and package dependencies

---

ci/launch_e2e_ara.sh

This commit allow write access to the
badge status image.

ci: allow write all to badge_status

---

kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_openshift/defaults/main.yml

This commit upgrades the OKD version
to the latest.

feat: upgrade OKD to 4.12

---

ci/launch_e2e.sh
kubeinit/roles/kubeinit_cdk/defaults/main.yml
kubeinit/roles/kubeinit_cdk/tasks/main.yml
kubeinit/roles/kubeinit_cdk/templates/bundle.yml.j2
kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_prepare/tasks/gather_kubeinit_facts.yml

This commit upgrades the CDK version that is deployed to use jammy and k8s 1.26.

feat: upgrade CDK version to 1.26/jammy

---

kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_libvirt/tasks/deploy_windows_guest.yml

This commit makes sure the virtio image
is defined in a fdefault variable.

fix: make consistent the virtio image iso

---

kubeinit/roles/kubeinit_eks/tasks/post_configure_guest.yml
kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_rke/defaults/main.yml

This commit upgrades the deployed RKE version
to the latest available.

fix: update RKE to latest

---

kubeinit/roles/kubeinit_eks/defaults/main.yml
kubeinit/roles/kubeinit_eks/tasks/main.yml
kubeinit/roles/kubeinit_eks/tasks/post_configure_guest.yml
kubeinit/roles/kubeinit_eks/tasks/prepare_cluster.yml

This commit makes sure the installer gets
the latest revision available.

fix: run EKS with the latest revision available

---

ci/launch_e2e.py

This commit updates the GH CI results
tracker id.

ci: update GH tracker id

---

.ansible-lint
.github/workflows/distro_test.yml
ci/sanity.sh
ci/units.sh
kubeinit/galaxy.yml
kubeinit/requirements.yml
kubeinit/roles/kubeinit_apps/templates/win_sampleapp.yml.j2
kubeinit/roles/kubeinit_eks/tasks/main.yml
kubeinit/roles/kubeinit_eks/tasks/post_configure_guest.yml
kubeinit/roles/kubeinit_k8s/tasks/main.yml
kubeinit/roles/kubeinit_k8s/tasks/post_configure_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/cleanup_hypervisors.yml
kubeinit/roles/kubeinit_libvirt/tasks/deploy_centos_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/deploy_coreos_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/deploy_debian_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/deploy_ubuntu_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/deploy_windows_guest.yml
kubeinit/roles/kubeinit_prepare/tasks/gather_kubeinit_facts.yml
kubeinit/roles/kubeinit_services/tasks/00_create_service_pod.yml
test-requirements.txt
tox.ini

This commit disables the experimental
new lint checks.

ci: fix linter issues

---

.github/workflows/distro_test.yml
kubeinit/roles/kubeinit_libvirt/tasks/main.yml

This commit gets the logs after running
the distro_test job.

ci: include docker log after distro_test job

---

kubeinit/roles/kubeinit_libvirt/tasks/main.yml
kubeinit/roles/kubeinit_rke/tasks/prepare_cluster.yml

This commit makes sure the Kubernetes repositories are trusted.

fix: trust kubernetes repositories

---

ci/container_sync.sh
kubeinit/roles/kubeinit_k8s/defaults/main.yml
kubeinit/roles/kubeinit_k8s/tasks/post_configure_guest.yml
kubeinit/roles/kubeinit_k8s/templates/kube-flannel.yml.j2

This commit files the patch of the
/etc/cni/net.d/87-crio-bridge.conflist
with the current installed cri-o versions.

fix: fix cri-o cbr0 interface file path

---

kubeinit/README.md
kubeinit/roles/kubeinit_k8s/templates/kube-flannel.yml.j2

This commit includes the correct pluging mapping
for cni-conf.json

fix: bind flannel to crio

---

kubeinit/roles/kubeinit_openshift/defaults/main.yml

This commit upgrades de default
OKD version to the latest available.

chore: update to latest OKD 4.12

---

kubeinit/roles/kubeinit_cdk/tasks/main.yml
kubeinit/roles/kubeinit_eks/tasks/main.yml
kubeinit/roles/kubeinit_k8s/tasks/main.yml
kubeinit/roles/kubeinit_openshift/tasks/main.yml
kubeinit/roles/kubeinit_rke/tasks/main.yml

This commit adds kustomize by default in each distro.

feat: include kustomize

---

kubeinit/roles/kubeinit_eks/defaults/main.yml
kubeinit/roles/kubeinit_eks/tasks/post_configure_guest.yml
kubeinit/roles/kubeinit_k8s/tasks/post_configure_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/deploy_centos_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/deploy_coreos_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/deploy_debian_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/deploy_ubuntu_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/deploy_windows_guest.yml

This commit removes unused params for virt-install

fix: remove libvirt virt-install options that are not used

---

ci/install_gitlab_node.sh
kubeinit/roles/kubeinit_cdk/tasks/post_configure_guest.yml
kubeinit/roles/kubeinit_kid/tasks/post_configure_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/deploy_ubuntu_guest.yml

There is no podman service to start.

fix: do not start podman

---

molecule/molecule-requirements.yml
molecule/run.sh

This commit includes community.docker
for the molecule tests execution.

ci: include community.docker

---

ci/launch_e2e.py

This commit adds a new issue for logging CI results.

chore: add new GH issue

---

kubeinit/roles/kubeinit_openshift/defaults/main.yml

This commit updates OKD to the latest available version.

chore: update OKD

---

agent/setup.py
kubeinit/galaxy.yml
ui/app/version.py
ui/package.json

This commit releases a new minor version.

ci: release 2.2.1

---

ci/container_sync.sh

This commit makes sure the images
labels also match the hashes so
we make sure we have the latest image
for each hash.

ci: fix container images in quay

---

ci/container_sync.sh

This commit refers to the
correct image digest field.

ci: fix digest field
