kubeinit/roles/kubeinit_okd/defaults/main.yml

Swaps the variables within kubeinit_okd_dependencies. Client was given the Installer's URL, and vice versa.

fix: swapped variable names within kubeinit_okd_dependencies

---

.github/workflows/docs_build_pr.yml
.github/workflows/release.yml
docs/src/index.rst
docs/src/inventory_diagrams.rst
docs/src/playbook_diagrams.rst

This patch renders automatically the
inventory and supported playbooks
for the supported scenarios.

docs: add inventory and playbook diagrams

---

kubeinit/roles/kubeinit_okd/defaults/main.yml
kubeinit/roles/kubeinit_registry/tasks/10_configure.yml
kubeinit/roles/kubeinit_registry/tasks/20_mirror_okd.yml

This patch appends the disconnected install auth token
to the pullsecrets variable so its added to the pullSecret
install-config variable when deploying the OKD cluster.

fix: appends okd pullsecret to disconnected install

---

kubeinit/roles/kubeinit_submariner/tasks/10_join_clusters.yml

This patch makes fully usable the submariner job and the
CI deployment.

fix: include --image-override in the submariner playbook

---

ci/run.sh
ci/run_submariner.sh
kubeinit/roles/kubeinit_submariner/tasks/10_join_clusters.yml

Quotes in OEF blocks variable expansion which is the
default behavior inside of here-docs.
This was disabled by quoting the label (with single or double quotes).

fix: remove quotes from eof

---

ci/launch_submariner_operator.py
kubeinit/hosts/okd/inventory
kubeinit/roles/kubeinit_submariner/tasks/00_configure_common.yml
kubeinit/roles/kubeinit_submariner/tasks/10_join_clusters.yml

When deploying submariner the newly created
container images need to be tagged and pointed
to the local registry.

fix: pull from local registry explicitly

---

kubeinit/roles/kubeinit_registry/defaults/main.yml
kubeinit/roles/kubeinit_registry/tasks/00_install.yml
kubeinit/roles/kubeinit_registry/tasks/10_configure.yml
kubeinit/roles/kubeinit_submariner/tasks/00_configure_common.yml

This patch allows choosing between docker or podman in the
service machine when installing the local registry.

fix: allow docker and podman in the local registry container

---

docs/src/usage.rst
kubeinit/README.md
kubeinit/galaxy.yml
kubeinit/roles/kubeinit_registry/tasks/20_mirror_rke.yml

This patch releases 0.6.2 fix a major fix
for the new podman version breaking all distros
deployments.

chore: release 0.6.2

---

kubeinit/roles/kubeinit_okd/tasks/30_post_deployment_tasks.yml

There are some missing parameters that
needs to be adjusted in OKD 4.6 to deploy
single node clusters.

fix: add workarounds for 1 master OKD cluster

---

agent/requirements.txt

This patch removes the openshift requirement which is
not necesary.

fix: openshift sdk is not required

---

kubeinit/roles/kubeinit_eks/tasks/30_configure_worker_nodes.yml
kubeinit/roles/kubeinit_eks/tasks/40_post_deployment_tasks.yml
kubeinit/roles/kubeinit_libvirt/tasks/main.yml
kubeinit/roles/kubeinit_okd/tasks/main.yml
kubeinit/roles/kubeinit_validations/defaults/main.yml
kubeinit/roles/kubeinit_validations/tasks/20_libvirt_free_space.yml

By default libvirtd is not enabled
so the deployments might fail.
Also add a failsafe path for libvirt default
folder.

fix: make sure libvirtd is enabled

---

kubeinit/roles/kubeinit_okd/defaults/main.yml
kubeinit/roles/kubeinit_okd/tasks/30_post_deployment_tasks.yml

This includes a variable to wait or not until
the cluster converges, mostly the autoupdate
can take more than 1 hour to finish.

fix: allow not waiting for okd to converge

---

agent/setup.py
kubeinit/galaxy.yml
ui/app/version.py
ui/package.json

This PR releases kubeinit 1.0.0
with mutiple features amongs them
support for 5 kubernetes distributions,
multicluster and multinode deployments.

chore: release 1.0.0

---

kubeinit/roles/kubeinit_eks/tasks/20_configure_master_nodes.yml
kubeinit/roles/kubeinit_eks/tasks/30_configure_worker_nodes.yml
kubeinit/roles/kubeinit_eks/tasks/40_post_deployment_tasks.yml
kubeinit/roles/kubeinit_k8s/tasks/30_configure_worker_nodes.yml
kubeinit/roles/kubeinit_k8s/tasks/40_post_deployment_tasks.yml
kubeinit/roles/kubeinit_okd/tasks/20_check_nodes_ready.yml
kubeinit/roles/kubeinit_okd/tasks/main.yml
kubeinit/roles/kubeinit_rke/tasks/10_configure_service_nodes.yml

This PR renames correctly a task that checks that nodes are ready.

fix: name check nodes correctly

---

kubeinit/roles/kubeinit_libvirt/tasks/00_ovn_post_setup.yml

This PR aligns the OVN network parameters
with the values from the inventory files, currently
they are hardwired.

fix: align OVN network parameters with inventory variables

---

kubeinit/roles/kubeinit_libvirt/tasks/00_cleanup.yml
kubeinit/roles/kubeinit_libvirt/tasks/10_k8s_deploy_nodes.yml
kubeinit/roles/kubeinit_libvirt/tasks/10_okd_deploy_nodes.yml
kubeinit/roles/kubeinit_libvirt/tasks/10_rke_deploy_nodes.yml
kubeinit/roles/kubeinit_libvirt/tasks/main.yml

This PR makes sure we ssh proxy is configured once, also, cleaned
once in the first hypervisor.
Also makes sure each guest boots before continue, if we
create multiple guests at the same time libvirt may crash.

fix: cleanup and configure ssh proxy once and wait for guest

---

docs/src/usage.rst

This commit adds a playbook to clean the environment
in the documentation.
Closes: #180

docs: add the cleanup section

---

.github/workflows/release.yml

This commit moves the repo sync to the correct place.

fix: move GitLab mirror to sw release

---

.github/workflows/release.yml

This commit makes sure fetching the branches never returns 1.

fix: fetching all branches returns 1 if they already exists

---

kubeinit/roles/kubeinit_libvirt/tasks/00_ovn_post_setup.yml
kubeinit/roles/kubeinit_libvirt/tasks/main.yml

This PR checks that the external bridge is only
created in the node with the service node.

fix: run bridge check only in the external host

---

.gitlab-ci.yml
ci/launch_e2e_periodic.py

This commit splits the periodic job into multiple
jobs because it takes too much time to execute all the
posible scenarios in a single run.

fix: split periodic job in multiple smaller jobs

---

kubeinit/roles/kubeinit_cdk/tasks/00_bounce_packages.yml
kubeinit/roles/kubeinit_eks/tasks/00_bounce_packages.yml
kubeinit/roles/kubeinit_haproxy/templates/haproxy.cfg.j2
kubeinit/roles/kubeinit_k8s/tasks/00_bounce_packages.yml
kubeinit/roles/kubeinit_okd/tasks/00_bounce_packages.yml
kubeinit/roles/kubeinit_rke/tasks/00_bounce_packages.yml

This commit shifts the default 9000 port to
9090 because it might conflict with the default
cockpit port and disables ipv6 by default in
the guests.

fix: move haproxy port to 9090 and disable ipv6

---

kubeinit/roles/kubeinit_validations/tasks/40_libvirt_check_cpu_cores.yml
kubeinit/roles/kubeinit_validations/tasks/70_libvirt.yml

This commit checks that per each physical
core there can be up to 4 virtual cores.

feat: validate physical cores per guest

---

kubeinit/roles/kubeinit_okd/tasks/10_configure_service_nodes.yml
kubeinit/roles/kubeinit_okd/tasks/30_check_bootstrap_complete.yml

This commit store the install manifests
before rendering the ignition files for
having a better debugging.

fix: backup install manifests

---

kubeinit/roles/kubeinit_libvirt/templates/detach.sh.j2

This commit validates that the detach script install the
correct packages when creating the OVS bridge.

fix: check if the distro is Centos or Fedora in the detach script

---

kubeinit/roles/kubeinit_libvirt/templates/detach.sh.j2

This commit checks that the detach script
fails if they hypervisors are Ubuntu or
Debian as they are not yet supported.

fix: include error for non supported distros

---

kubeinit/roles/kubeinit_nfs/tasks/main.yml
tox.ini

This commit refreshes the way we generate the yaml artifacts for
managed-nfs-storage and also now uses that storage class to allocate
the volume for the image registry.

fix: update nfs role to latest k8s sig practice

---

kubeinit/roles/kubeinit_nfs/tasks/main.yml

This commit fixes a race condition in the CI,
we try to patch resources that might not exists.

fix: wait for image registry resource exists

---

kubeinit/roles/kubeinit_okd/tasks/10_configure_service_nodes.yml

This commit enables mastersSchedulable when there
are no worker nodes in the cluster.

fix: enable mastersSchedulable if no workers

---

kubeinit/roles/kubeinit_nfs/tasks/main.yml

This commit adds an ignore_errors when waiting for the NFS resources
to start.

fix: add ignore_errors when waiting for nfs resources to start

---

kubeinit/roles/kubeinit_okd/tasks/10_configure_service_nodes.yml

This commit disables or enables the master nodes as schedulable
depending only if there are or not worker nodes.

fix: enable or disable master schedulable depending on worker nodes

---

kubeinit/roles/kubeinit_libvirt/templates/detach.sh.j2

This commit enfoces the parameters
when calling the detach script.

fix: enforce detach parameters

---

docs/src/usage.rst

This commit fixes the documentation about how to clean the
environment.

docs: include all_nodes and fix the task path for cleaning

---

kubeinit/roles/kubeinit_nfs/tasks/main.yml

This adds a higher timeout when pathing the imageregistry
operator.

fix: add a timeout to the imageregistry provider commands

---

kubeinit/roles/kubeinit_apache/tasks/main.yml
kubeinit/roles/kubeinit_bind/tasks/main.yml
kubeinit/roles/kubeinit_haproxy/tasks/main.yml
kubeinit/roles/kubeinit_registry/tasks/00_install.yml

This patch fixes showing the podman login
password in the Ansible logs.

fix: securize podman login

---

kubeinit/roles/kubeinit_apache/tasks/main.yml
kubeinit/roles/kubeinit_bind/tasks/main.yml
kubeinit/roles/kubeinit_haproxy/tasks/main.yml
kubeinit/roles/kubeinit_libvirt/tasks/00_prepare.yml
kubeinit/roles/kubeinit_libvirt/templates/docker_io_pass.j2
kubeinit/roles/kubeinit_registry/tasks/00_install.yml

This commit changes the docker.io auth from CLI to
use a text file.

fix: login to docker.io from text file auth

---

kubeinit/roles/kubeinit_apache/tasks/main.yml
kubeinit/roles/kubeinit_bind/tasks/main.yml
kubeinit/roles/kubeinit_haproxy/tasks/main.yml
kubeinit/roles/kubeinit_registry/tasks/00_install.yml

This commit moves to shell the podman login
commands as the dont work correctly with
different OS distros.

fix: move to shell and sort parameters

---

ci/launch_e2e_periodic.py

This commit fixes a nit in the ci scripts
that causes k8s periodic job to run cdk.

fix: replace wrong ci strings

---

kubeinit/roles/kubeinit_submariner/tasks/10_secondary_deployment.yml

This commit fixes the podman login to configure
the secondary submariner cluster.

fix: adjust podman login in secondary cluster

---

kubeinit/roles/kubeinit_k8s/defaults/main.yml
kubeinit/roles/kubeinit_k8s/tasks/20_configure_common.yml

This commit updates k8s from 1.18 to 1.20
and configures extra variables for choosing
the distro and the k8s version to be deployed.

feat: bump k8s version to 1.20

---

kubeinit/roles/kubeinit_submariner/tasks/10_secondary_deployment.yml

It is still required to have the authentication
details in the .docker folder defore pushing
to the local registry.

fix: include registry auth in .docker

---

kubeinit/roles/kubeinit_rke/tasks/10_configure_common.yml

This commit removes the docker upgrade command,
we need to pin a specific version.

fix: do not upgrade Docker

---

kubeinit/roles/kubeinit_submariner/defaults/main.yml
kubeinit/roles/kubeinit_submariner/tasks/00_broker_deployment.yml
kubeinit/roles/kubeinit_submariner/tasks/10_secondary_deployment.yml
kubeinit/roles/kubeinit_submariner/tasks/20_check_connection.yml
kubeinit/roles/kubeinit_submariner/tasks/30_subctl_verify.yml

This commit adds the correct nodes labels for
the submariner operator to work in HA when its
possible.

fix: adjust submariner labels based on the workers number

---

kubeinit/roles/kubeinit_submariner/tasks/00_broker_deployment.yml

This commit changes subctl--linux-amd64 with
subctl--linux-amd64 because is the new name
for this binary.

fix: change subctl--linux-amd64 with subctl

---

kubeinit/roles/kubeinit_submariner/defaults/main.yml
kubeinit/roles/kubeinit_submariner/tasks/30_subctl_verify.yml

The CI triggers the subctl verify command
just after the cluster is deployed. Let's give
some time to the cluster to converge prior the test.

feat: sleep for x seconds before the subctl verify.

---

.github/workflows/docs_build_pr.yml
.github/workflows/linters.yml
.github/workflows/molecule.yml
.github/workflows/release.yml
.github/workflows/stale.yml
ci/launch_e2e_periodic.py

This commit adjust the GitHub jobs to use the
same status check (build 3.8).

fix: make jobs to force use latest ubuntu and python 3.8

---

Dockerfile

By default we use python:slim
to deploy the kubeinit container.
This commit makes explicit where to
pull from.

fix: pull from docker

---

Dockerfile
kubeinit/roles/kubeinit_prepare/tasks/prepare_localhost.yml

This commit adds iproute2 to the packages being installed
in the container image.  This provides the 'ip' command that
ansible depends on to gather network facts.

fix: add iproute2 install to Dockerfile

---

ci/run_kubeinit.sh
ci/run_periodic.sh
kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_libvirt/tasks/10_cleanup.yml
kubeinit/roles/kubeinit_libvirt/tasks/30_linux_bridge_setup.yml
kubeinit/roles/kubeinit_libvirt/tasks/main.yml
kubeinit/roles/kubeinit_prepare/defaults/main.yml
kubeinit/roles/kubeinit_prepare/tasks/10_cleanup.yml
kubeinit/roles/kubeinit_prepare/tasks/20_ovn_install.yml
kubeinit/roles/kubeinit_prepare/tasks/40_ovn_setup.yml
kubeinit/roles/kubeinit_prepare/tasks/50_ovn_post_setup.yml
kubeinit/roles/kubeinit_prepare/tasks/main.yml

This commit moves the OVN tasks to the
prepare role, this is because the OVN
setup is not dependant on libvirt.

feat: move OVN setup to the prepare role

---

kubeinit/roles/kubeinit_eks/tasks/30_configure_master_nodes.yml
kubeinit/roles/kubeinit_libvirt/tasks/10_cleanup.yml
kubeinit/roles/kubeinit_libvirt/tasks/60_deploy_coreos_guest.yml
kubeinit/roles/kubeinit_nexus/tasks/main.yml
kubeinit/roles/kubeinit_nfs/tasks/main.yml
kubeinit/roles/kubeinit_okd/tasks/10_configure_service_nodes.yml
kubeinit/roles/kubeinit_okd/tasks/50_post_deployment_tasks.yml
kubeinit/roles/kubeinit_prepare/tasks/10_cleanup.yml
kubeinit/roles/kubeinit_prepare/tasks/prepare_localhost.yml
kubeinit/roles/kubeinit_registry/tasks/main.yml
kubeinit/roles/kubeinit_validations/tasks/10_libvirt_free_space.yml
kubeinit/roles/kubeinit_validations/tasks/20_libvirt_available_ram.yml
kubeinit/roles/kubeinit_validations/tasks/30_libvirt_check_cpu_cores.yml

Using set -o pipefail only works when the executable is /bin/bash.

Use /bin/bash when using set -o pipefail

---

kubeinit/roles/kubeinit_libvirt/tasks/10_cleanup.yml

This commit makes sure all the inventory guests are destroyed
before undefining them.

fix: make sure VMs are destroyed before undefining

---

kubeinit/roles/kubeinit_validations/tasks/10_libvirt_free_space.yml

This commit removes the dependency with the localization
of the 'df' command, in English it returns 'Avail' and in
Spanish 'Disp'.
Closes: #337

fix: do not depend on the language output of df

---

.github/workflows/docs_build_pr.yml
.github/workflows/release.yml

This commit fixes the job default branch
for the GH actions pointing to master.

fix: adjust workflows to point to main

---

kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_libvirt/tasks/10_cleanup.yml
kubeinit/roles/kubeinit_libvirt/tasks/60_deploy_centos_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/60_deploy_coreos_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/60_deploy_ubuntu_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/main.yml
kubeinit/roles/kubeinit_prepare/defaults/main.yml
kubeinit/roles/kubeinit_prepare/tasks/10_cleanup.yml
kubeinit/roles/kubeinit_prepare/tasks/20_ovn_install.yml
kubeinit/roles/kubeinit_prepare/tasks/40_ovn_setup.yml
kubeinit/roles/kubeinit_prepare/tasks/50_ovn_post_setup.yml
kubeinit/roles/kubeinit_prepare/tasks/main.yml
kubeinit/roles/kubeinit_prepare/tasks/prepare_hypervisor.yml
kubeinit/roles/kubeinit_prepare/tasks/prepare_podman.yml
kubeinit/roles/kubeinit_prepare/templates/docker_io_pass.j2

This commit addresses the following issues:
- Move all hypervisor preparation to prepare_hypervisor.yml
- Move installation of package dependencies from libvirt role
to the prepare role.
- Undefine VMs and remove storage for all VMs that were found.
- Use first 3 characters from node names instead of 2 since both
controller and compute start with co.
- Change docker password environment and ansible variable value
from the actual password to the path of a file containing the
password.

fix: rework changes so that ovn network installs consistently

---

kubeinit/roles/kubeinit_cdk/tasks/20_configure_service_nodes.yml
kubeinit/roles/kubeinit_eks/tasks/10_configure_service_nodes.yml
kubeinit/roles/kubeinit_k8s/tasks/10_configure_service_nodes.yml
kubeinit/roles/kubeinit_prepare/tasks/50_ovn_post_setup.yml
kubeinit/roles/kubeinit_prepare/tasks/prepare_groups.yml
kubeinit/roles/kubeinit_prepare/tasks/prepare_localhost.yml
kubeinit/roles/kubeinit_prepare/tasks/prepare_podman.yml
kubeinit/roles/kubeinit_rke/tasks/20_configure_service_nodes.yml

This commit removes the need for creating new files and simplifies
the flow through the prepare podman tasks.  Additional minor cleanup
changes to reduce complexity of future deliveries.

fix: cleanup prepare_podman tasks

---

kubeinit/roles/kubeinit_cdk/tasks/20_configure_service_nodes.yml
kubeinit/roles/kubeinit_eks/tasks/10_configure_service_nodes.yml
kubeinit/roles/kubeinit_haproxy/tasks/main.yml
kubeinit/roles/kubeinit_k8s/tasks/10_configure_service_nodes.yml
kubeinit/roles/kubeinit_okd/tasks/10_configure_service_nodes.yml
kubeinit/roles/kubeinit_registry/tasks/main.yml
kubeinit/roles/kubeinit_rke/tasks/20_configure_service_nodes.yml

WHen pulling from external sources, the pods/containers
creation might fail.
This commit adds a retry for such scenarios.
Closes: #346

fix: retry when pods/containers fail to be created

---

kubeinit/roles/kubeinit_apache/tasks/main.yml

This commit makes sure the apache folder exists
before creating the apache containter.

fix: make sure the apache folder exists before deploying the container

---

kubeinit/roles/kubeinit_libvirt/tasks/60_deploy_centos_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/60_deploy_coreos_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/60_deploy_ubuntu_guest.yml
kubeinit/roles/kubeinit_services/tasks/00_create_service_pod.yml

We need to be able to deploy multiple
clusters in the same OVN network.
This commit allows to deploy two different
clusters (different distros) in the same
net.

fix: allow use distro in veth interface

---

kubeinit/roles/kubeinit_cdk/defaults/main.yml
kubeinit/roles/kubeinit_cdk/tasks/10_configure_common.yml
kubeinit/roles/kubeinit_cdk/tasks/20_configure_service_nodes.yml
kubeinit/roles/kubeinit_cdk/tasks/60_deploy_cdk.yml
kubeinit/roles/kubeinit_cdk/tasks/main.yml
kubeinit/roles/kubeinit_cdk/templates/bundle.yml.j2
kubeinit/roles/kubeinit_eks/tasks/10_configure_service_nodes.yml
kubeinit/roles/kubeinit_eks/tasks/50_post_deployment_tasks.yml
kubeinit/roles/kubeinit_k8s/tasks/10_configure_service_nodes.yml
kubeinit/roles/kubeinit_k8s/tasks/50_post_deployment_tasks.yml
kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_okd/tasks/prepare_virtual_services.yml
kubeinit/roles/kubeinit_rke/tasks/20_configure_service_nodes.yml
kubeinit/roles/kubeinit_rke/tasks/70_post_deployment_services_tasks.yml

This commit restores the cdk support to an operational
state.  There are some configurations that still have
some issues, but the cluster deployments should function
again and the cluster issues can be investigated further.

fix: re-enabled cdk deployment

---

kubeinit/roles/kubeinit_cdk/tasks/60_deploy_cdk.yml

This commit unblocks the CI and only check that the
cluster is healthy.

fix: check whether the cluster is healthy

---

ci/install_gitlab_node.sh

The first time we install the node the sqlite DB
does not exists.

fix: remove rm command

---

kubeinit/roles/kubeinit_eks/tasks/30_configure_control_plane_nodes.yml

This commit makes sure the EKS distro has the correct perms in
the OK before referencing it.

fix: make sure PK has the correct perms

---

kubeinit/roles/kubeinit_prepare/tasks/50_ovn_post_setup.yml
kubeinit/roles/kubeinit_services/tasks/00_create_service_pod.yml
kubeinit/roles/kubeinit_services/tasks/10_create_provision_container.yml
kubeinit/roles/kubeinit_services/tasks/prepare_credentials.yml

pipefail is not present within the sh shell and produces the following error message:
```
Illegal option -o pipefail
```

fix: set Ansible shell to Bash when using pipefail

---

kubeinit/playbooks/submariner-subctl-verify.yml
kubeinit/playbooks/submariner.yml

This commit aligns the submariner deployment playbook
with the distros deployment playbooks.

fix: organize submariner playbooks

---

kubeinit/hosts/cdk/inventory
kubeinit/hosts/eks/inventory
kubeinit/hosts/k8s/inventory
kubeinit/hosts/kid/inventory
kubeinit/hosts/okd/inventory

This commit adds the 1.20 repos for cri-o
in OKD 4.7

fix: use k8s 1.2 in OKD 4.7

---

.github/workflows/distro_test.yml

This commit makes the playbook to run as
the runner user.

fix: run the e2e test as the runner user

---

kubeinit/playbook.yml
kubeinit/roles/kubeinit_prepare/tasks/main.yml
kubeinit/roles/kubeinit_prepare/tasks/prepare_hypervisor.yml

Side-effect is there is now a new play task to start and stop on: `task-gather-hypervisor-facts`

fix: move tasks to gather hypervisor facts out of hypervisor_hosts play

---

Dockerfile

By moving the the COPY directive to a lower position, we can save
rebuilds of the container when we are actively working on the code.
As the packages are installed before the copy directive, the base
container needs to be built only once.
Signed-off-by: Raghavendra Talur <raghavendra.talur@gmail.com>

perf: optimize dockerfile

---

ci/install_gitlab_node.sh

This commit updates the CI install script
to use the host IP instead of localhost
to reference nyctea.

ci: use hostname IP instead of localhost

---

kubeinit/README.md

This commit includes the distro_test job result
after every push in the main project's readme.

ci: include the distro deploy badge in the readme

---

ci/periodic_jobs.md.j2

This commit fixes the periodic job status page newlines.

ci: fix lines spaces

---

ci/kubeinit_ci_utils.py
ci/periodic_jobs.md.j2

This commit aligns the periodic CI
jobs with the jobs supported for testing
the PRs.

ci: make consistent the CI jobs list

---

ci/launch_e2e.py
ci/periodic_jobs.md.j2

This commit adds some context information
for the labels used in the CI for checking
PRs.

ci: add label info to periodic jobs

---

ci/install_gitlab_node.sh
kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_libvirt/tasks/main.yml
kubeinit/roles/kubeinit_prepare/tasks/gather_host_facts.yml
kubeinit/roles/kubeinit_services/tasks/prepare_credentials.yml

We should not install or force firewalld status
to configure the cluster, this commit check the
firewalld status before executing the tasks.

fix: make cluster changes based on firewalld status

---

Dockerfile

Using "--no-cache-dir" flag in pip install ,make sure dowloaded packages
by pip don't cached on system . This is a best practise which make sure
to fetch ftom repo instead of using local cached one . Further , in case
of Docker Containers , by restricing caching , we can reduce image size.
In term of stats , it depends upon the number of python packages
multiplied by their respective size . e.g for heavy packages with a lot
of dependencies it reduce a lot by don't caching pip packages.
Further , more detail information can be found at
https://medium.com/sciforce/strategies-of-docker-images-optimization-2ca9cc5719b6
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

chore: Use --no-cache-dir flag to pip in Dockerfiles, to save space

---

kubeinit/roles/kubeinit_cdk/tasks/60_deploy_cdk.yml

This commit increases the timeout when waiting
for the cluster to converge, this is useful when
deploying in old HW so the cluster will take
more time to be healthy.

fix: increase timeout for CDK deployments

---

ci/launch_e2e_ara.sh

This commit enables an empty href
replacement with the main jobs URL.

ci: allow empty ref in main link

---

ci/kubeinit_ci_utils.py
ci/launch_e2e.sh
ci/periodic_jobs.md.j2
ci/render_periodic_jobs_page.py

This commit revert adding the job dates in the
GItHub job page, this is because then after
every job execution the page will be re-rendered
creating continous pull requests.

ci: do not update the .md job page

---

.github/workflows/docs_build_pr.yml
.github/workflows/release.yml
docs/src/contributing.rst
docs/src/images/plantuml/github_workflow.plantuml

This commit adds information about
how the CI runs, and includes a
mechanism to autorender plantuml
diagrams directly.

docs: include end-to-end workflow

---

.github/workflows/docs_build_pr.yml
.github/workflows/release.yml
docs/src/contributing.rst
docs/src/static/css/custom.css

PNG files always look better on
web, so let's use that extension by
default.

docs: use always png on plantuml

---

ci/launch_e2e.py

On every force-push we lose the CI
information from previous executions
this commit includes a comment once each
job finish.

ci: add comment per job execution

---

kubeinit/roles/kubeinit_cdk/tasks/main.yml
kubeinit/roles/kubeinit_cdk/tasks/post_deployment_tasks.yml
kubeinit/roles/kubeinit_eks/tasks/main.yml
kubeinit/roles/kubeinit_eks/tasks/post_deployment_tasks.yml
kubeinit/roles/kubeinit_k8s/tasks/main.yml
kubeinit/roles/kubeinit_k8s/tasks/post_deployment_tasks.yml
kubeinit/roles/kubeinit_kid/tasks/main.yml
kubeinit/roles/kubeinit_kid/tasks/post_deployment_tasks.yml
kubeinit/roles/kubeinit_nfs/tasks/main.yml
kubeinit/roles/kubeinit_okd/tasks/main.yml
kubeinit/roles/kubeinit_okd/tasks/post_deployment_tasks.yml
kubeinit/roles/kubeinit_prepare/tasks/gather_host_facts.yml
kubeinit/roles/kubeinit_rke/tasks/main.yml
kubeinit/roles/kubeinit_rke/tasks/post_deployment_tasks.yml

also cleanup redundant authorized_key distribution as it is already part of creating the guest vm

refactor: move tasks from post-deployment to deploy-cluster

---

kubeinit/roles/kubeinit_libvirt/tasks/cleanup_libvirt.yml
kubeinit/roles/kubeinit_libvirt/tasks/create_network.yml
kubeinit/roles/kubeinit_prepare/tasks/cleanup_hypervisors.yml
kubeinit/roles/kubeinit_services/tasks/00_create_service_pod.yml

The first time we deploy in new baremetal hosts
after installing the required packages to install
the SDN the path is not updated in runtime, this
makes the deployment to fail the first time.

fix: use full path when calling OVN/OVN commands

---

kubeinit/galaxy.yml
kubeinit/requirements.yml
kubeinit/roles/kubeinit_cdk/tasks/post_configure_guest.yml
kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_libvirt/tasks/cleanup_libvirt.yml
kubeinit/roles/kubeinit_libvirt/tasks/create_network.yml
kubeinit/roles/kubeinit_libvirt/tasks/deploy_debian_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/deploy_ubuntu_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/main.yml
kubeinit/roles/kubeinit_prepare/tasks/prepare_podman.yml
kubeinit/roles/kubeinit_rke/tasks/prepare_cluster.yml

In Debian 11 is not yet published the list of OVN
packages to deploy the cluster.
This commit removes virt-top as is not available anymore,
and enables the testing repos.

fix: remove virt-top from Debian 11 and add testing repos

---

kubeinit/inventory
kubeinit/roles/kubeinit_apache/tasks/main.yml
kubeinit/roles/kubeinit_bind/tasks/main.yml
kubeinit/roles/kubeinit_bind/templates/create-external-ingress.sh.j2
kubeinit/roles/kubeinit_cdk/tasks/main.yml
kubeinit/roles/kubeinit_dnsmasq/tasks/main.yml
kubeinit/roles/kubeinit_eks/tasks/main.yml
kubeinit/roles/kubeinit_haproxy/tasks/main.yml
kubeinit/roles/kubeinit_k8s/tasks/main.yml
kubeinit/roles/kubeinit_libvirt/defaults/main.yml
kubeinit/roles/kubeinit_libvirt/tasks/cleanup_libvirt.yml
kubeinit/roles/kubeinit_libvirt/tasks/create_network.yml
kubeinit/roles/kubeinit_libvirt/tasks/download_cloud_images.yml
kubeinit/roles/kubeinit_nexus/tasks/main.yml
kubeinit/roles/kubeinit_okd/tasks/main.yml
kubeinit/roles/kubeinit_prepare/tasks/cleanup_hypervisors.yml
kubeinit/roles/kubeinit_prepare/tasks/deploy_cluster.yml
kubeinit/roles/kubeinit_prepare/tasks/gather_host_facts.yml
kubeinit/roles/kubeinit_prepare/tasks/gather_kubeinit_facts.yml
kubeinit/roles/kubeinit_prepare/tasks/main.yml
kubeinit/roles/kubeinit_prepare/tasks/post_deployment.yml
kubeinit/roles/kubeinit_prepare/tasks/prepare_cluster.yml
kubeinit/roles/kubeinit_prepare/tasks/prepare_groups.yml
kubeinit/roles/kubeinit_prepare/tasks/prepare_podman.yml
kubeinit/roles/kubeinit_registry/tasks/main.yml
kubeinit/roles/kubeinit_services/tasks/00_create_service_pod.yml
kubeinit/roles/kubeinit_services/tasks/create_provision_container.yml
kubeinit/roles/kubeinit_services/tasks/main.yml
kubeinit/roles/kubeinit_services/tasks/prepare_credentials.yml
kubeinit/roles/kubeinit_validations/tasks/main.yml

This commit adds support for multiple clusters deployed from the
same inventory.  Most changes are to names of resources that need
to be distinct so that clusters can co-exist.

refactor: support multiple clusters per inventory

---

docs/src/architecture.rst
docs/src/usage.rst

This commit includes the documentation
for reaching both internal and external
resources of the cluster.
Closes: #480

docs: include steps to reach the services pod

---

docs/src/static/css/custom.css
docs/src/static/parsers/xhtml1-symbol.txt
docs/src/usage.rst

This commit includes some unicode helpers
to add symbols to the docs when they are needed.

docs: include unicode assets

---

docs/src/static/css/custom.css
docs/src/static/parsers/xhtml1-lat1.txt
docs/src/static/parsers/xhtml1-special.txt
docs/src/usage.rst

This commit includes the extra symbols available in
the rst pages.

docs: include extra symbols

---

ci/kubeinit_ci_utils.py

This commit fixes the CI job index with the
correct date and job ID per PR job.

fix: adjust date and job id

---

kubeinit/roles/kubeinit_okd/defaults/main.yml
kubeinit/roles/kubeinit_okd/tasks/main.yml
kubeinit/roles/kubeinit_okd/templates/install-config.yaml.j2

This commit moves the default CNI
cluster network provider to
OVNKubernetes as it will be the
eventual default.

fix: move to OVNKubernetes

---

kubeinit/galaxy.yml
kubeinit/requirements.yml
setup/group_vars/all.yml
setup/inventory
setup/playbook.yml
setup/roles/kubeinit_setup/tasks/cleanup_deployment.yml
setup/roles/kubeinit_setup/tasks/gather_host_facts.yml
setup/roles/kubeinit_setup/tasks/gather_setup_facts.yml
setup/roles/kubeinit_setup/tasks/main.yml
setup/roles/kubeinit_setup/tasks/prepare_environment.yml
setup/roles/kubeinit_setup/templates/ssh-config.j2

This commit adds a new setup folder that contains an inventory
and playbook that can be used to initialize a new ansible env
where kubeinit has been setup and is ready for immediate use
for deployments, testing, development, etc.

feat: add ansible setup for kubeinit

---

ci/install_gitlab_node.sh
ci/launch_e2e.py

This commit includes the libselinux-python3 package in
the Fedora/CentOS/RHEL hosts.

ci: include libselinux-python3 in selinux based hosts

---

.github/workflows/render_periodic_jobs_status_page.yml

This commit includes the b2sdk dependency
for the GitHub status page render job.

ci: include b2sdk in the Github jobs status

---

ci/install_gitlab_node.sh

This commit includes the latest key types supported by
default.

ci: include the key type

---

docs/src/usage.rst
kubeinit/group_vars/all.yml
kubeinit/group_vars/kubeinit_env.yml

This commit includes all group variables supported
to the docs automatically.

docs: include all vars

---

ci/gitlab_ci_trigger.sh
ci/gitlab_ci_trigger_test.sh
ci/launch_e2e.py
ci/launch_e2e.sh

This commit includes the --job_type=pr
in all the script calls for testing PRs.

ci: include the job type in all PR triggers

---

ci/launch_e2e.py

This commit removes a wrong cast
on the PR id, this variable might be int or
string.

ci: remove int cast

---

ci/kubeinit_ci_utils.py

This commit includes the required
file path when displaying what files
will be deleted from B2.

ci: use folder path instead of filename

---

kubeinit/roles/kubeinit_apps/templates/sampleapp.yml.j2

This commit pulls from quay (quay.io/packit/nginx-unprivileged)
the Nginx image to run the sample app.
This will run NGINX as a non root, unprivileged user.
Notable differences with respect to the official
NGINX image include:
- The default NGINX listen port is now 8080 instead of 80.
- The default NGINX user directive in /etc/nginx/nginx.conf has been removed.
- The default NGINX PID has been moved from /var/run/nginx.pid to /tmp/nginx.pid. *Change _temp_path variables to /tmp/.

ci: use nginx unprivileged in the sampleapp

---

ci/launch_e2e.sh

This commit enables Windows workers in
the k8s-1-1-1 deployment spec for the CI.

ci: enable windows workers in the CI

---

ci/kubeinit_ci_utils.py

This commit allows to run workloads in
controller nodes when there are no
compute nodes.

ci: remove unsupported scenarios from CDK

---

ci/gitlab_ci_trigger.sh
ci/launch_e2e.py

This commit allows to use the nolog
label in the e2e jobs so the result is not uploaded
to b2. This is useful to reduce the load on the
CI CDN if there is no need to review the logs results.

ci: allow skipping upload logs to b2

---

ci/launch_e2e.py

This commit prevents from updating the resulting
CI job URL if the logs are not uploaded to b2.

ci: do not update job URL if not uploading logs

---

.ansible-lint
ci/launch_e2e.sh
docs/src/roles/role-kubeinit_openstack.rst
kubeinit/inventory.yml
kubeinit/roles/kubeinit_openshift/tasks/post_deployment_tasks.yml
kubeinit/roles/kubeinit_openstack/README.md
kubeinit/roles/kubeinit_openstack/defaults/main.yml
kubeinit/roles/kubeinit_openstack/handlers/main.yml
kubeinit/roles/kubeinit_openstack/meta/main.yml
kubeinit/roles/kubeinit_openstack/molecule/default/converge.yml
kubeinit/roles/kubeinit_openstack/molecule/default/molecule.yml
kubeinit/roles/kubeinit_openstack/molecule/default/verify.yml
kubeinit/roles/kubeinit_openstack/tasks/main.yml
kubeinit/roles/kubeinit_openstack/tasks/podified_controlplane.yml
kubeinit/roles/kubeinit_openstack/tasks/standalone_compute.yml
kubeinit/roles/kubeinit_openstack/vars/main.yml
kubeinit/roles/kubeinit_prepare/tasks/build_hypervisors_group.yml

This commit includes the ability to
run custom roles at the end of the
deployments. As an example we run a
custom openstack role.

feat: include dynamic extra roles

---

kubeinit/roles/kubeinit_libvirt/tasks/deploy_coreos_guest.yml

Currently defining the VM on the deploy_coreos_guest task does
not add the path of the qcow2 disk. This makes the variable
kubeinit_libvirt_target_image_dir useless.
This patch add the path to the disk in the same way as is defined
on the deploy_centos_guest task.

fix: add qcow2 full path deploying coreos as guest

---

.github/workflows/docs_build.yml

This commit removes the workaround for
the issue building the docs site.

fix: remove ansible-playbook-grapher workaround

---

ci/ansible/roles/kubeinit_ci/tasks/gather_ci_facts.yml
ci/launch_e2e.sh
docs/src/roles/role-kubeinit_ooonextgen.rst
kubeinit/roles/kubeinit_libvirt/tasks/70_check_nodes_up.yml
kubeinit/roles/kubeinit_ooonextgen/README.md
kubeinit/roles/kubeinit_ooonextgen/defaults/main.yml
kubeinit/roles/kubeinit_ooonextgen/handlers/main.yml
kubeinit/roles/kubeinit_ooonextgen/meta/main.yml
kubeinit/roles/kubeinit_ooonextgen/molecule/default/converge.yml
kubeinit/roles/kubeinit_ooonextgen/molecule/default/molecule.yml
kubeinit/roles/kubeinit_ooonextgen/molecule/default/verify.yml
kubeinit/roles/kubeinit_ooonextgen/tasks/main.yml
kubeinit/roles/kubeinit_ooonextgen/tasks/podified_controlplane.yml
kubeinit/roles/kubeinit_ooonextgen/tasks/standalone_compute.yml
kubeinit/roles/kubeinit_ooonextgen/tasks/standalone_tripleo.yml
kubeinit/roles/kubeinit_ooonextgen/vars/main.yml
kubeinit/roles/kubeinit_openshift/tasks/main.yml
kubeinit/roles/kubeinit_openstack/defaults/main.yml

This commit includes the folder to add a new deployment driver,
as for now deployments are only supported on KVM hosts.
The previous openstack role is renamed to be consumed as a user
application.

feat: include OpenStack deployment driver

---

kubeinit/roles/kubeinit_libvirt/tasks/deploy_centos_guest.yml
kubeinit/roles/kubeinit_libvirt/tasks/download_cloud_images.yml

This commit removes the update shortcut from
the virt-customize command when deploying
Stream 9 images.

fix: remove update from customize

---

ci/kubeinit_ci_utils.py

This commit includes a new label for testing
the deployments on top of OpenStack.

ci: include a new label for OpenStack

---

kubeinit/roles/kubeinit_ooonextgen/tasks/standalone_tripleo.yml

This commit fixes the usage of the date hash
in the tripleo-repos package.

fix: remove hash from tripleo-repos install

---

kubeinit/roles/kubeinit_ooonextgen/tasks/standalone_tripleo.yml

This commit includes again the python tripleo client to deploy the standalone node

fix: include the python tripleo client

---

kubeinit/roles/kubeinit_apache/tasks/main.yml
kubeinit/roles/kubeinit_haproxy/tasks/main.yml
kubeinit/roles/kubeinit_registry/tasks/main.yml

This commit reduces the number of references
to docker.io to avoid the limit-rate issue.

fix: change docker.io by quay.io

---

.github/workflows/docs_build.yml

This commit changes the tool
used for rendering the PNG images
from the SVG sources in the documentation.

ci: use rsvg-convert for docs

---

kubeinit/roles/kubeinit_prepare/tasks/prepare_podman.yml

This commit makes sure that the default capabilities map in
containers common is consistent across different versions
and distributions in the Hypervisors

fix: make sure default_capabilities is consistent

---

ci/launch_e2e_ara.sh

This commit moves the badge files
instead of copying it.

ci: move badge status instead of copy

---

ci/container_sync.sh
kubeinit/roles/kubeinit_k8s/defaults/main.yml
kubeinit/roles/kubeinit_k8s/templates/kube-flannel.yml.j2

This commit upgrades the Kubernetes and flannel
version deployed in the vanilla scenario
to their corresponding latest stable versions.

feat: upgrade Kubernetes and Flannel to latest stable

---

.github/workflows/quay_mirror.yml

This commit makes the container mirror
script to run in evrey push.

ci: sync up containers on push

---

kubeinit/roles/kubeinit_eks/tasks/post_configure_guest.yml
kubeinit/roles/kubeinit_libvirt/defaults/main.yml

This commit makes sure the installer gets
the latest revision available.

fix: run EKS with the latest revision available

---

kubeinit/roles/kubeinit_libvirt/tasks/deploy_ubuntu_guest.yml

This commit make sure the official K8s repos
are trusted.

fix: allow unsecure Kubernetes repos

---

kubeinit/roles/kubeinit_libvirt/tasks/deploy_ubuntu_guest.yml

This commit fixes a duplicated key nit in the
libvirt driver role.

fix: removeduplicated key

---

molecule/run.sh

This commit removes the extra argument passed in pytest when running the molecule testing suite.

ci: remove extra ansible arguments

---

kubeinit/roles/kubeinit_k8s/tasks/post_configure_guest.yml

This commit fixes the current path for the subnet in /etc/cni/net.d/87-podman-bridge.conflist

fix: fix subnet path for /etc/cni/net.d/87-podman-bridge.conflist

---

ci/gitlab_merge_request.sh
ci/launch_e2e.sh

The version specified is not a valid version according to PEP 440. This may not work as expected with newer versions of setuptools, pip, and PyPI.

fix: string in revision error PEP 440

---

kubeinit/roles/kubeinit_rke/tasks/post_configure_guest.yml

This commit fixes the name of the correct
docker.socket name instead of podman.socket.

fix: use the correct socket service

---

ci/release.sh

This commit checks the NG
galaxy endpoint for publishing the
collection.

ci: test new galaxy endpoint

---

ci/release.sh

This commit points back the galaxy endpoint
to the production API.

ci: revert to main galaxy API

---

agent/setup.py
ci/release.sh
kubeinit/galaxy.yml
ui/app/version.py
ui/package.json

This commit pushes a new version for
the collection and uses the NG API v3

ci: build 2.2.2 and use Galaxy v3 API

---

ci/release.sh

This commit removes the pagination when getting
the published collection versions.

ci: remove pagination when publishing in Galaxy
